// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/property-metadata/main.tsp.
// Do not edit this file by hand.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CssPropertyMetadataV1Json {
    pub schema_version: String,
    pub product: String,
    pub source: CssPropertyMetadataSourceV1Json,
    pub custom_property_policy: CssCustomPropertyPolicyV1Json,
    pub properties: Vec<CssPropertyMetadataRecordV1Json>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CssPropertyMetadataSourceV1Json {
    pub package: String,
    pub version: String,
    pub source_path: String,
    pub tool: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CssCustomPropertyPolicyV1Json {
    pub inherited: bool,
    pub initial_value: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CssPropertyMetadataRecordV1Json {
    pub property_id: String,
    pub canonical_name: String,
    pub inherited: bool,
    pub initial_value: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CssPropertyMetadataStaticV1 {
    pub schema_version: &'static str,
    pub product: &'static str,
    pub source: CssPropertyMetadataSourceStaticV1,
    pub custom_property_policy: CssCustomPropertyPolicyStaticV1,
    pub properties: &'static [CssPropertyMetadataRecordStaticV1],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CssPropertyMetadataSourceStaticV1 {
    pub package: &'static str,
    pub version: &'static str,
    pub source_path: &'static str,
    pub tool: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CssCustomPropertyPolicyStaticV1 {
    pub inherited: bool,
    pub initial_value: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CssPropertyMetadataRecordStaticV1 {
    pub property_id: &'static str,
    pub canonical_name: &'static str,
    pub inherited: bool,
    pub initial_value: &'static str,
}

pub const CSS_PROPERTY_METADATA_V1: CssPropertyMetadataStaticV1 = CssPropertyMetadataStaticV1 {
    schema_version: "1",
    product: "omena-cascade.property-metadata",
    source: CssPropertyMetadataSourceStaticV1 {
        package: "@webref/css",
        version: "8.6.0",
        source_path: "rust/crates/omena-spec-audit/data/webref-grammar.json",
        tool: "scripts/generate-engine-v2-contract-idl.ts",
    },
    custom_property_policy: CssCustomPropertyPolicyStaticV1 {
        inherited: true,
        initial_value: "guaranteed-invalid",
    },
    properties: CSS_PROPERTY_METADATA_RECORDS_V1,
};

pub const CSS_PROPERTY_METADATA_RECORDS_V1: &[CssPropertyMetadataRecordStaticV1] = &[
    CssPropertyMetadataRecordStaticV1 {
        property_id: "background-color",
        canonical_name: "background-color",
        inherited: false,
        initial_value: "transparent",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "border-color",
        canonical_name: "border-color",
        inherited: false,
        initial_value: "transparent",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "border-style",
        canonical_name: "border-style",
        inherited: false,
        initial_value: "none",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "border-width",
        canonical_name: "border-width",
        inherited: false,
        initial_value: "0",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "box-shadow",
        canonical_name: "box-shadow",
        inherited: false,
        initial_value: "none",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "caret-color",
        canonical_name: "caret-color",
        inherited: false,
        initial_value: "transparent",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "color",
        canonical_name: "color",
        inherited: true,
        initial_value: "canvastext",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "cursor",
        canonical_name: "cursor",
        inherited: true,
        initial_value: "auto",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "direction",
        canonical_name: "direction",
        inherited: true,
        initial_value: "initial",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "display",
        canonical_name: "display",
        inherited: false,
        initial_value: "none",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "font",
        canonical_name: "font",
        inherited: true,
        initial_value: "initial",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "font-family",
        canonical_name: "font-family",
        inherited: true,
        initial_value: "serif",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "font-size",
        canonical_name: "font-size",
        inherited: true,
        initial_value: "medium",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "font-style",
        canonical_name: "font-style",
        inherited: true,
        initial_value: "normal",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "font-variant",
        canonical_name: "font-variant",
        inherited: true,
        initial_value: "normal",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "font-weight",
        canonical_name: "font-weight",
        inherited: true,
        initial_value: "normal",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "letter-spacing",
        canonical_name: "letter-spacing",
        inherited: true,
        initial_value: "normal",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "line-height",
        canonical_name: "line-height",
        inherited: true,
        initial_value: "normal",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "margin",
        canonical_name: "margin",
        inherited: false,
        initial_value: "0",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "opacity",
        canonical_name: "opacity",
        inherited: false,
        initial_value: "1",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "outline-color",
        canonical_name: "outline-color",
        inherited: false,
        initial_value: "transparent",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "padding",
        canonical_name: "padding",
        inherited: false,
        initial_value: "0",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "text-align",
        canonical_name: "text-align",
        inherited: true,
        initial_value: "start",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "text-indent",
        canonical_name: "text-indent",
        inherited: true,
        initial_value: "0",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "text-shadow",
        canonical_name: "text-shadow",
        inherited: false,
        initial_value: "none",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "text-transform",
        canonical_name: "text-transform",
        inherited: true,
        initial_value: "none",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "visibility",
        canonical_name: "visibility",
        inherited: true,
        initial_value: "visible",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "white-space",
        canonical_name: "white-space",
        inherited: true,
        initial_value: "normal",
    },
    CssPropertyMetadataRecordStaticV1 {
        property_id: "word-spacing",
        canonical_name: "word-spacing",
        inherited: true,
        initial_value: "normal",
    },
];
