pub(crate) mod color;
pub(crate) mod css_module_global;
pub(crate) mod custom_property;
pub(crate) mod import_inline;
pub(crate) mod number;
pub(crate) mod reachability;
pub(crate) mod rule_merge;
pub(crate) mod shorthand;
pub(crate) mod static_eval;
