// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-napi/main.tsp.
// Do not edit this file by hand.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

pub type EngineNapiTransformExecutionContextV0Json =
    omena_query::OmenaQueryTransformExecutionContextV0;
pub type EngineNapiTargetTransformOptionsV0Json = omena_query::OmenaQueryTargetTransformOptionsV0;
pub type EngineNapiStyleSourceInputV0Json = omena_query::OmenaQueryStyleSourceInputV0;
pub type EngineNapiStylePackageManifestV0Json = omena_query::OmenaQueryStylePackageManifestV0;
pub type EngineNapiSourceDocumentInputV0Json = omena_query::OmenaQuerySourceDocumentInputV0;
pub type EngineNapiSourceMissingSelectorDiagnosticCandidateV0Json =
    omena_query::OmenaQuerySourceMissingSelectorDiagnosticCandidateV0;
pub type EngineNapiClassnamesBindBindingsV0Json = Vec<String>;
pub type EngineNapiConsumerBuildSummaryV0Json = omena_query::OmenaQueryConsumerBuildSummaryV0;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum EngineNapiBoundaryErrorKindV0Json {
    #[serde(rename = "parse-error")]
    ParseError,
    #[serde(rename = "serialize-error")]
    SerializeError,
    #[serde(rename = "unsupported-mode")]
    UnsupportedMode,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EngineNapiBoundaryErrorV0Json {
    pub kind: EngineNapiBoundaryErrorKindV0Json,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_name: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EngineNapiEngineInputV2Json {
    pub version: String,
    pub workspace: serde_json::Value,
    pub sources: Vec<serde_json::Value>,
    pub styles: Vec<serde_json::Value>,
    pub type_facts: Vec<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EngineNapiSourceImportedStyleBindingInputV0Json {
    pub binding: String,
    pub style_uri: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EngineNapiBoundarySurfaceV0Json {
    pub context: EngineNapiTransformExecutionContextV0Json,
    pub target_options: EngineNapiTargetTransformOptionsV0Json,
    pub input: EngineNapiEngineInputV2Json,
    pub sources: Vec<EngineNapiStyleSourceInputV0Json>,
    pub package_manifests: Vec<EngineNapiStylePackageManifestV0Json>,
    pub source_documents: Vec<EngineNapiSourceDocumentInputV0Json>,
    pub candidates: Vec<EngineNapiSourceMissingSelectorDiagnosticCandidateV0Json>,
    pub imported_style_bindings: Vec<EngineNapiSourceImportedStyleBindingInputV0Json>,
    pub classnames_bind_bindings: EngineNapiClassnamesBindBindingsV0Json,
    pub build_summary: serde_json::Value,
    pub boundary_error: EngineNapiBoundaryErrorV0Json,
}
