use std::collections::{BTreeMap, BTreeSet};

mod explain;
pub use explain::{
    OmenaQueryExplainAvailabilityV0, OmenaQueryExplainCapabilityV0,
    OmenaQueryExplainFactReferenceV0, OmenaQueryExplainFactV0, OmenaQueryExplainFactValueV0,
    OmenaQueryExplainInputV0, OmenaQueryExplainResponseV0, OmenaQueryExplainSourceSpanV0,
    OmenaQueryExplainSymbolKindV0, OmenaQueryExplainTargetV0, explain_omena_query,
    explain_omena_query_tree_shake_for_style_source, explain_omena_query_tree_shake_unavailable,
};

use omena_bridge::{
    DesignTokenExternalDeclarationCandidateScopeV0, DesignTokenWorkspaceDeclarationFactV0,
    StyleSemanticGraphSummaryV0,
    collect_omena_bridge_design_token_workspace_declarations_from_source,
    summarize_omena_bridge_style_semantic_graph_from_source,
    summarize_omena_bridge_style_semantic_graph_from_source_with_scoped_workspace_declarations,
};
pub use omena_bridge::{
    OmenaBridgeExternalSifCacheContextV0 as OmenaQueryExternalSifCacheContextV0,
    generate_omena_bridge_sif_for_resolved_style_path,
    generate_omena_bridge_sif_for_resolved_style_path_with_cache_context,
};
pub use omena_bridge::{
    SourceBindingDeclFactV0 as OmenaQuerySourceBindingDeclFactV0,
    SourceBindingIndexV0 as OmenaQuerySourceBindingIndexV0,
    SourceBindingScopeFactV0 as OmenaQuerySourceBindingScopeFactV0,
    SourceBindingStyleImportFactV0 as OmenaQuerySourceBindingStyleImportFactV0,
    SourceClassExpressionNodeFactV0 as OmenaQuerySourceClassExpressionNodeFactV0,
    SourceClassUtilityBindingFactV0 as OmenaQuerySourceClassUtilityBindingFactV0,
    SourceClassValueUniverseAxisV0 as OmenaQuerySourceClassValueUniverseAxisV0,
    SourceClassValueUniverseEntryV0 as OmenaQuerySourceClassValueUniverseEntryV0,
    SourceClassnamesBindUtilityBindingFactV0 as OmenaQuerySourceClassnamesBindUtilityBindingFactV0,
    SourceControlFlowGraphCaptureV0 as OmenaQuerySourceControlFlowGraphCaptureV0,
    SourceDeclaresStyleImportFactV0 as OmenaQuerySourceDeclaresStyleImportFactV0,
    SourceDeclaresUtilityBindingFactV0 as OmenaQuerySourceDeclaresUtilityBindingFactV0,
    SourceDomainClassReferenceFactV0 as OmenaQuerySourceDomainClassReferenceFactV0,
    SourceExpressionTargetsModuleFactV0 as OmenaQuerySourceExpressionTargetsModuleFactV0,
    SourceFlowBindingRefV0 as OmenaQuerySourceFlowBindingRefV0,
    SourceFlowBlockGraphSnapshotV0 as OmenaQuerySourceFlowBlockGraphSnapshotV0,
    SourceFlowBlockSnapshotV0 as OmenaQuerySourceFlowBlockSnapshotV0,
    SourceImportDeclarationSummaryV0 as OmenaQuerySourceImportDeclarationSummaryV0,
    SourceImportDeclarationV0 as OmenaQuerySourceImportDeclarationV0,
    SourceImportedStyleBindingV0 as OmenaQuerySourceImportedStyleBindingV0,
    SourceInlineStyleDeclarationFactV0 as OmenaQuerySourceInlineStyleDeclarationFactV0,
    SourceLanguageParserBoundarySummaryV0 as OmenaQuerySourceLanguageParserBoundarySummaryV0,
    SourceLanguageParserDescriptorV0 as OmenaQuerySourceLanguageParserDescriptorV0,
    SourceModuleSpecifierFactV0 as OmenaQuerySourceModuleSpecifierFactV0,
    SourceScopeContainsDeclFactV0 as OmenaQuerySourceScopeContainsDeclFactV0,
    SourceScopeParentFactV0 as OmenaQuerySourceScopeParentFactV0,
    SourceSelectorReferenceFactV0 as OmenaQuerySourceSelectorReferenceFactV0,
    SourceSelectorReferenceMatchKindV0 as OmenaQuerySourceSelectorReferenceMatchKindV0,
    SourceStyleAccessUsesStyleImportFactV0 as OmenaQuerySourceStyleAccessUsesStyleImportFactV0,
    SourceStyleImportResolvesModuleFactV0 as OmenaQuerySourceStyleImportResolvesModuleFactV0,
    SourceStylePropertyAccessFactV0 as OmenaQuerySourceStylePropertyAccessFactV0,
    SourceSymbolRefUsesDeclFactV0 as OmenaQuerySourceSymbolRefUsesDeclFactV0,
    SourceSyntaxIndexV0 as OmenaQuerySourceSyntaxIndexV0,
    SourceTypeFactProviderUnavailableFactV0 as OmenaQuerySourceTypeFactProviderUnavailableFactV0,
    SourceTypeFactTargetV0 as OmenaQuerySourceTypeFactTargetV0,
    SourceUtilityUsesStyleImportFactV0 as OmenaQuerySourceUtilityUsesStyleImportFactV0,
    summarize_omena_bridge_source_language_parser_boundary_v0 as summarize_omena_query_source_language_parser_boundary_v0,
};
pub type OmenaQuerySourceTypeFactControlFlowGraphV0 =
    omena_bridge::OmenaBridgeSourceTypeFactControlFlowGraphV0;
pub use omena_cross_file_summary::{
    BatchHypergraphConnectivityOracle, HypergraphClosureMode, HypergraphClosurePath,
    HypergraphIFDSSummaryEdgeV0, OmenaCrossFileGraphDeltaEdgeV0, OmenaCrossFileGraphDeltaV0,
    OmenaCrossFileLinearProvenanceV0, OmenaCrossFileSummaryNodeRoleV0,
    OmenaCrossFileSummaryRawEdgeKindV0, OmenaCrossFileSummaryViewReportV0,
    OmenaQueryCrossFileSccEvidenceV0, OmenaQueryCrossFileSummaryCapabilitiesV0,
    OmenaQueryCrossFileSummaryEdgeKindCountV0, OmenaQueryCrossFileSummaryEdgeV0,
    OmenaQueryCrossFileSummaryV0, OmenaQueryUnifiedCrossFileHypergraphV0,
    OmenaQueryUnifiedCrossFileSccReportV0, OmenaUnifiedHypergraphConnectivityOracle,
    ReverseDependencyIndexV0, UnifiedHypergraphEdgeKindV0, UnifiedHypergraphHyperedgeV0,
    apply_reverse_dependency_delta_v0, collect_directed_graph_cycles,
    collect_directed_graph_cycles_with_work_cap, collect_directed_graph_sccs,
    collect_hypergraph_transitive_closure_paths,
    collect_hypergraph_transitive_closure_paths_with_mode, collect_reachable_node_ids,
    collect_reachable_node_ids_bitset, diagnostics_read_set_for_target_v0,
    parse_cross_file_summary_node_role_v0, parse_cross_file_summary_raw_edge_kind_v0,
    recompute_cross_file_summary_raw_edge_kind_counts_v0, reverse_dependency_closure_v0,
    reverse_dependency_index_from_edges_v0, summarize_cross_file_graph_delta_v0,
    summarize_cross_file_summary_view_v0, summarize_omena_query_unified_cross_file_hypergraph,
    summarize_omena_query_unified_cross_file_scc_report, tabulate_hypergraph_ifds_summary_edges,
};
pub use omena_parser::{
    ModuleIdV0 as OmenaQueryModuleIdV0, OpenWorldSnapshotV0 as OmenaQueryOpenWorldSnapshotV0,
    ParseTreeNodeV0 as OmenaQueryParseTreeNodeV0, ParserByteSpanV0, ParserPositionV0,
    ParserRangeV0, StyleDialect as OmenaParserStyleDialect, StyleLanguage,
};
use omena_parser::{
    ParsedSassModuleEdgeFactKind, ParsedSassSymbolFactKind, ParsedSelectorFactKind,
    ParsedVariableFactKind,
};

pub fn parse_style_document_typed_v0(
    source: &str,
    dialect: OmenaParserStyleDialect,
) -> OmenaQueryParseTreeNodeV0 {
    omena_cst_typed::parse_style_document_typed_v0(source, dialect)
}

pub fn syntax_node_id_for_omena_query_style_source(
    style_source: &str,
    dialect: OmenaParserStyleDialect,
) -> String {
    let parsed = omena_parser::parse(style_source, dialect);
    omena_parser::syntax_node_id(&parsed.syntax())
        .as_str()
        .to_string()
}
use omena_query_checker_orchestrator::{
    CATEGORICAL_FEATURE_GATE_V0, CATEGORICAL_LAYER_MARKER_V0, CATEGORICAL_SCHEMA_VERSION_V0,
    DesignSystemEdgeKindCountV0, DesignSystemProjectSummaryInputV0,
    build_omena_query_checker_design_system_model_from_project_summary_v0,
    compare_omena_query_checker_design_system_models_for_invariant_v0,
};
pub use omena_query_checker_orchestrator::{
    DesignSystemInvariantSummaryV0 as OmenaQueryCategoricalDesignSystemInvariantSummaryV0,
    DesignSystemModelV0 as OmenaQueryCategoricalDesignSystemModelV0,
    query_product_diagnostic_checker_rule_code_name_v0 as omena_query_checker_rule_code_name_for_diagnostic_v0,
};
pub use omena_query_core::EngineInputV2 as OmenaQueryEngineInputV2;
pub use omena_query_core::{
    AbstractClassValueV0, AbstractPropertyValueCandidateV0, AbstractPropertyValueNarrowingV0,
    AbstractPropertyValueV0, AbstractValueDomainSummaryV0, CascadeContextV0,
    CascadeDimensionalRefinementBridgeV0, CascadeValueFamilyMemberV0, ClassExpressionInputV2,
    ClassValueFlowAnalysisV0, ClassValueFlowIncrementalAnalysisV0, EngineInputV2,
    ExpressionDomainCallSiteFlowAnalysisV0, ExpressionDomainControlFlowAnalysisV0,
    ExpressionDomainFlowAnalysisV0, ExpressionDomainProvenanceExplanationsV0,
    ExpressionDomainReducedProductIterationV0, ExpressionSemanticsCanonicalProducerSignalV0,
    ExpressionSemanticsQueryFragmentsV0, ExternalStringTypeFactsV0, FactPrecision,
    IncrementalEditDistancePriorityInputV0, IncrementalGraphInputV0,
    IncrementalInvalidationPriorityPlanV0, IncrementalNodeInputV0, IncrementalRevisionV0,
    Lin01ProvenanceSemiringV0, LinearProvenancePathV0, LinearProvenanceV0,
    NaturalCountProvenanceSemiringV0, OMENA_QUERY_CURRENT_SCHEMA_VERSION,
    OMENA_QUERY_CURRENT_SCHEMA_VERSION_LABEL, OmenaIncrementalDatabaseV0,
    OmenaQueryAnalysisPrecisionV0, OmenaQueryAnalysisResultV0,
    OmenaQueryExpressionDomainFlowRuntimeV0,
    OmenaQueryExpressionDomainIncrementalFlowAnalysisEntryV0,
    OmenaQueryExpressionDomainIncrementalFlowAnalysisV0,
    OmenaQueryExpressionDomainSelectorPrecisionV0,
    OmenaQueryExpressionDomainSelectorProjectionEntryV0,
    OmenaQueryExpressionDomainSelectorProjectionV0, OmenaQueryFragmentBundleV0,
    OmenaResolverSourceResolutionRuntimeIndexV0, OmenaSalsaDatabaseV0, OmenaWorkspaceSnapshotIdV0,
    PolynomialProvenanceProjectionV0, PolynomialProvenanceTermV0, PolynomialProvenanceV0,
    PolynomialProvenanceVariableV0, PositionV2, ProvenanceSemiringLawReportV0, RangeV2,
    ReducedClassValueProductIterationV0, ReducedClassValueProductV0, RefinementPropertyPredicateV0,
    SelectorProjectionCertaintyV0, SelectorUsageCanonicalProducerSignalV0,
    SelectorUsageQueryFragmentsV0, SourceAnalysisInputV2, SourceDocumentV2,
    SourceResolutionCanonicalProducerSignalV0, SourceResolutionQueryFragmentsV0, StringTypeFactsV2,
    StyleAnalysisInputV2, StyleDocumentV2, StyleSelectorV2, TypeFactEntryV2,
    abstract_class_value_from_facts, abstract_class_value_kind, canonicalize_css_value,
    derive_cascade_restriction_maps_v0, iterate_reduced_class_value_product_constraints,
    join_abstract_class_values, narrow_abstract_property_value_for_cascade_branch,
    narrow_abstract_property_value_for_pseudo_state, prefix_suffix_class_value,
    snapshot_from_graph_input, split_top_level_value_arguments,
    split_top_level_whitespace_value_components,
    summarize_cascade_dimensional_refinement_bridge_v0, summarize_cascade_value_family_v0,
    summarize_omena_query_core_abstract_value_domain,
    summarize_omena_query_expression_domain_call_site_flow_analysis,
    summarize_omena_query_expression_domain_control_flow_analysis,
    summarize_omena_query_expression_domain_flow_analysis,
    summarize_omena_query_expression_domain_incremental_flow_analysis,
    summarize_omena_query_expression_domain_incremental_flow_analysis_result,
    summarize_omena_query_expression_domain_provenance_explanations,
    summarize_omena_query_expression_domain_reduced_product_iteration,
    summarize_omena_query_expression_domain_selector_projection,
    summarize_omena_query_expression_domain_selector_projection_with_precision,
    summarize_omena_query_expression_semantics_canonical_producer_signal,
    summarize_omena_query_expression_semantics_query_fragments,
    summarize_omena_query_fragment_bundle,
    summarize_omena_query_selector_usage_canonical_producer_signal,
    summarize_omena_query_selector_usage_query_fragments,
    summarize_omena_query_source_resolution_canonical_producer_signal,
    summarize_omena_query_source_resolution_query_fragments,
    summarize_omena_query_source_resolution_runtime,
    summarize_polynomial_provenance_from_linear_v0, verify_provenance_semiring_laws_on_fixtures,
};
pub use omena_query_transform_runner::{
    CustomPropertyLeastFixedPointSummaryV0 as OmenaQueryCustomPropertyLeastFixedPointSummaryV0,
    MinifyPassClassificationV0 as OmenaQueryMinifyPassClassificationV0,
    MinifyPassProfileClassV0 as OmenaQueryMinifyPassProfileClassV0,
    PrettyFormatOptionsV0 as OmenaQueryPrettyFormatOptionsV0,
    RollbackReceiptV0 as OmenaQueryRollbackReceiptV0, RollbackScopeV0 as OmenaQueryRollbackScopeV0,
    StyleDialect as OmenaQueryTransformStyleDialect,
    TargetFeatureSupportV0 as OmenaQueryTargetFeatureSupportV0,
    TargetTransformOptionsV0 as OmenaQueryTargetTransformOptionsV0,
    TransformBuildProfileV0 as OmenaQueryTransformBuildProfileV0,
    TransformBundleAssetUrlRewriteSummaryV0 as OmenaQueryTransformBundleAssetUrlRewriteSummaryV0,
    TransformBundleEdgeKind,
    TransformBundleSourceSummaryV0 as OmenaQueryTransformBundleSourceSummaryV0,
    TransformClassNameRewriteV0 as OmenaQueryTransformClassNameRewriteV0,
    TransformCssModuleComposesResolutionV0 as OmenaQueryTransformCssModuleComposesResolutionV0,
    TransformCssModuleValueResolutionV0 as OmenaQueryTransformCssModuleValueResolutionV0,
    TransformDecision as OmenaQueryTransformDecisionV0,
    TransformDesignTokenRouteV0 as OmenaQueryTransformDesignTokenRouteV0,
    TransformExecutionContextV0 as OmenaQueryTransformExecutionContextV0,
    TransformExecutionSummaryV0 as OmenaQueryTransformExecutionSummaryV0,
    TransformImportInlineV0 as OmenaQueryTransformImportInlineV0,
    TransformModuleEvaluationNativeEditV0 as OmenaQueryTransformModuleEvaluationNativeEditV0,
    TransformModuleEvaluationNativeReplacementV0 as OmenaQueryTransformModuleEvaluationNativeReplacementV0,
    TransformModuleEvaluationOracleV0 as OmenaQueryTransformModuleEvaluationOracleV0,
    TransformModuleEvaluationV0 as OmenaQueryTransformModuleEvaluationV0,
    TransformPassExecutionOutcomeV0 as OmenaQueryTransformPassExecutionOutcomeV0,
    TransformPrintArtifactV0, TransformPrintMode as OmenaQueryTransformPrintMode,
    TransformPrintOptionsV0 as OmenaQueryTransformPrintOptionsV0,
    TransformSemanticPreservationDecisionV0 as OmenaQueryTransformSemanticPreservationDecisionV0,
    TransformSourceMapCompositionV0 as OmenaQueryTransformSourceMapCompositionV0,
    TransformSourceMapV3V0 as OmenaQueryTransformSourceMapV3V0,
    TransformTargetQueryPlanV0 as OmenaQueryTransformTargetQueryPlanV0,
    TransformVendorPrefixPolicyV0 as OmenaQueryTransformVendorPrefixPolicyV0,
    closed_world_minify_build_profile as closed_world_omena_query_minify_build_profile,
    compare_transform_css_semantics_v0 as compare_omena_query_transform_css_semantics_v0,
    compose_transform_source_map_v3_with_upstream_map as compose_omena_query_transform_source_map_v3_with_upstream_map,
    conservative_target_options as conservative_omena_query_target_options,
    default_minify_build_profiles as default_omena_query_minify_build_profiles,
    default_minify_pass_classifications as default_omena_query_minify_pass_classifications,
    default_print_options as default_omena_query_transform_print_options,
    modern_feature_support as modern_omena_query_target_feature_support,
    print_transform_cst_source_with_dialect_and_pretty_options as print_omena_query_transform_source_with_pretty_options,
    rewrite_omena_transform_bundle_asset_urls_in_source,
    safe_minify_build_profile as safe_omena_query_minify_build_profile,
    semantic_minify_build_profile as semantic_omena_query_minify_build_profile,
    summarize_omena_transform_bundle_from_source,
};
use omena_query_transform_runner::{
    EggRewriteSourceWitnessV0, TransformBundleAssetUrlRewriteSummaryV0,
    TransformBundleSourceSummaryV0, TransformEggPlanV0, TransformExecutionContextV0,
    TransformExecutionSummaryV0, TransformPassExecutionOutcomeV0, TransformPassKind,
    TransformPassPlanV0, TransformSourceMapSegmentV0, TransformTargetPlanV0,
    all_transform_pass_kinds, execute_egg_rewrite_witnesses_for_css_source,
    execute_transform_passes_on_source_with_dialect_and_context,
    plan_egg_rewrite_passes_for_source, plan_target_transforms, plan_target_transforms_from_query,
    plan_transform_passes, print_transform_execution_artifact_with_dialect_and_source,
    serialize_transform_source_map_v3_with_source_contents,
    summarize_static_css_custom_property_fixed_point_from_source, transform_source_map_point,
};
#[cfg(feature = "lawvere-trace")]
pub use omena_query_transform_runner::{
    LawvereDifferentialCommutativityWitnessV0 as OmenaQueryLawvereDifferentialCommutativityWitnessV0,
    LawvereModelTraceV0 as OmenaQueryLawvereModelTraceV0,
    ReorderabilityCertificateV0 as OmenaQueryLawvereReorderabilityCertificateV0,
    TransformPassParallelPlanV0 as OmenaQueryLawvereTransformPassParallelPlanV0,
};
#[cfg(feature = "lawvere-trace")]
use omena_query_transform_runner::{
    evaluate_lawvere_reorderability_with_differential_corpus,
    execute_transform_passes_on_source_with_lawvere_trace_and_dialect,
    plan_transform_passes_parallel_lawvere_layers,
};
use omena_resolver::{
    OmenaResolverBoundaryStateKindV0, OmenaResolverBoundaryStateV0, OmenaResolverBoundaryTopV0,
    OmenaResolverBundlerPathAliasMappingV0, OmenaResolverCanonicalUrlV0,
    OmenaResolverStyleModuleConfirmationOptionsV0, OmenaResolverStylePackageManifestV0,
    OmenaResolverTsconfigPathMappingV0, omena_resolver_boundary_state_for_unresolved_reference_v0,
    resolve_omena_resolver_style_module_source,
    summarize_omena_resolver_style_module_resolution_with_confirmation_inputs,
    summarize_omena_resolver_style_module_resolution_with_load_path_roots,
};
pub use omena_resolver::{
    OmenaResolverStyleModuleConfirmationIdentityIndexV0,
    OmenaResolverStyleModuleDiskCandidateIdentityV0,
    OmenaResolverStyleResolutionPolicyStepV0 as OmenaQueryStyleResolutionPolicyStepV0,
    OmenaResolverStyleResolutionPolicyV0 as OmenaQueryStyleResolutionPolicyV0,
    build_omena_resolver_style_module_confirmation_identity_index,
    invalidate_omena_resolver_style_identity_cache, omena_resolver_style_identity_generation,
    summarize_omena_resolver_style_resolution_policy_v0 as summarize_omena_query_style_resolution_policy_v0,
};
#[cfg(feature = "test-support")]
pub use omena_resolver::{
    omena_resolver_style_identity_index_build_count_for_test,
    omena_resolver_style_identity_index_build_work_count_for_test,
    reset_omena_resolver_style_identity_cache_for_test,
};
pub use omena_scss_eval::{
    OmenaScssEvalCallReturnIrSummaryV0 as OmenaQueryScssEvalCallReturnIrSummaryV0,
    OmenaScssEvalControlFlowIrSummaryV0 as OmenaQueryScssEvalControlFlowIrSummaryV0,
    OmenaScssEvalControlFlowPruneReachabilityV0 as OmenaQueryScssEvalControlFlowPruneReachabilityV0,
    OmenaScssEvalControlFlowValueAnalysisV0 as OmenaQueryScssEvalControlFlowValueAnalysisV0,
    OmenaScssEvalNativeCssFunctionCallEvaluationSurfaceV0 as OmenaQueryScssEvalNativeCssFunctionCallEvaluationSurfaceV0,
    OmenaScssEvalNativeCssFunctionSurfaceV0 as OmenaQueryScssEvalNativeCssFunctionSurfaceV0,
    OmenaScssEvalNativeCssIfFunctionDecisionSurfaceV0 as OmenaQueryScssEvalNativeCssIfFunctionDecisionSurfaceV0,
    OmenaScssEvalNativeCssStaticEditPlanV0 as OmenaQueryScssEvalNativeCssStaticEditPlanV0,
};
use omena_semantic::StyleContextIndexV0;
use serde::{Deserialize, Serialize};

macro_rules! omena_query_evidence_graph_provenance {
    ($($label:expr),* $(,)?) => {
        crate::types::project_omena_query_provenance_from_evidence_graph(&[$($label),*])
    };
}

mod boundary;
mod sdk_diagnostics;
mod sdk_error;
mod sdk_workflow_contract_idl_generated;
mod source;
mod style;
#[cfg(test)]
mod tests;
mod types;

pub use sdk_diagnostics::{
    execute_omena_sdk_diagnostics_debug_workflow, execute_omena_sdk_diagnostics_workflow,
};
pub use sdk_error::{OmenaError, omena_error_from_boundary_encoding};
pub use sdk_workflow_contract_idl_generated::{
    OmenaCliResponseEnvelopeV0, OmenaErrorClassV0, OmenaErrorContextV0, OmenaErrorRecoverabilityV0,
    OmenaErrorSeverityV0, OmenaErrorV0, OmenaSdkBuildRequestV0, OmenaSdkBuildResponseV0,
    OmenaSdkDiagnosticsDebugReportV0, OmenaSdkDiagnosticsRequestV0, OmenaSdkDiagnosticsResponseV0,
    OmenaSdkDiagnosticsSummaryV0, OmenaSdkErrorEnvelopeV0, OmenaSdkExplainPositionV0,
    OmenaSdkExplainRequestV0, OmenaSdkExplainResponseV0, OmenaSdkQueryRequestV0,
    OmenaSdkQueryResponseV0, OmenaSdkResponsePartitionV0, OmenaSdkSnapshotRequestV0,
    OmenaSdkSnapshotResponseV0,
};

pub use boundary::{
    OmenaQueryCanonicalFormInput, OmenaQueryNativeCssEvaluatorSummaryV0,
    OmenaQueryScssEvaluatorControlFlowOracleCorpusSummaryV0,
    OmenaQueryScssEvaluatorControlFlowSummaryV0, OmenaQueryStaticLifExportsSummaryV0,
    OmenaQueryStaticStylesheetEvaluatorOracleCorpusSummaryV0,
    OmenaQueryStaticStylesheetEvaluatorSummaryV0, check_omena_query_schema_version,
    summarize_omena_query_boundary, summarize_omena_query_canonical_form,
    summarize_omena_query_design_system_minimum_description,
    summarize_omena_query_evaluation_runtime,
    summarize_omena_query_native_css_evaluator_from_engine_input,
    summarize_omena_query_native_css_evaluator_from_source,
    summarize_omena_query_sass_module_conformance_v0, summarize_omena_query_schema_version_policy,
    summarize_omena_query_scss_evaluator_control_flow_from_engine_input,
    summarize_omena_query_scss_evaluator_control_flow_from_source,
    summarize_omena_query_scss_evaluator_control_flow_oracle_corpus,
    summarize_omena_query_selected_query_adapter_capabilities,
    summarize_omena_query_static_lif_exports_from_engine_input,
    summarize_omena_query_static_lif_exports_from_source,
    summarize_omena_query_static_stylesheet_evaluator_from_engine_input,
    summarize_omena_query_static_stylesheet_evaluator_from_source,
    summarize_omena_query_static_stylesheet_evaluator_oracle_corpus,
};
pub use source::{
    OmenaQueryBridgeExternalSifResolutionV0, OmenaQueryBundlerPathAliasMappingV0,
    OmenaQuerySourcePrecisionReferenceV0, OmenaQueryStyleModuleDiskCandidateIdentityV0,
    OmenaQueryStyleResolutionInputsV0, OmenaQueryTsconfigPathMappingV0,
    canonicalize_omena_query_source_selector_references,
    collect_omena_query_vue_style_module_bindings,
    load_omena_query_workspace_style_resolution_inputs,
    resolve_omena_query_bridge_external_sifs_for_seed_pairs,
    resolve_omena_query_bridge_external_sifs_for_style_sources,
    resolve_omena_query_source_precision_for_source, resolve_omena_query_style_uri_for_specifier,
    resolve_omena_query_style_uri_for_specifier_with_package_manifests,
    resolve_omena_query_style_uri_for_specifier_with_resolution_inputs,
    summarize_omena_query_source_binding_index,
    summarize_omena_query_source_binding_index_for_source_language,
    summarize_omena_query_source_control_flow_graph_for_source_language,
    summarize_omena_query_source_import_declarations,
    summarize_omena_query_source_import_declarations_for_source_language,
    summarize_omena_query_source_syntax_index,
    summarize_omena_query_source_syntax_index_for_source_language,
    summarize_omena_query_source_type_fact_control_flow_graph_for_source_language,
};
#[cfg(feature = "lawvere-trace")]
pub use style::execute_omena_query_transform_passes_from_source_with_lawvere_trace;
pub use style::{
    OmenaQueryBundlePlanInputV0, OmenaQueryCascadeSiteOutcomeV0, OmenaQueryCssModuleClassExportV0,
    OmenaQueryCssModuleClassReferenceV0, OmenaQueryCssModuleExportUsageStatusV0,
    OmenaQueryCssModuleExportUsageV0, OmenaQueryCssModuleIcssExportV0,
    OmenaQueryCssModuleInterfaceV0, OmenaQueryCssModulesExportUsageReportV0,
    OmenaQueryCssModulesInterfaceBundleV0, OmenaQueryCssModulesInterfaceSummaryViewV0,
    OmenaQueryCssModulesUnusedExportDiagnosticV0,
    OmenaQueryCssModulesUnusedExportSkipReasonCountV0,
    OmenaQueryCssModulesUnusedExportSkipReasonV0, OmenaQueryDynamicClassValueInputV0,
    OmenaQueryDynamicClassnameCallSiteV0, OmenaQueryDynamicClassnameMTierInputV0,
    OmenaQueryExternalModuleModeV0, OmenaQueryModuleInterfaceProjectionV0,
    OmenaQuerySassModuleRuleConfigurationSurfaceV0, OmenaQueryStyleCascadeNarrowingSubstrateV0,
    OmenaQueryStyleFrameRefreshFactsV0, OmenaQueryStyleFrameRefreshParseCacheV0,
    OmenaWorkspaceMonikerInput, attach_omena_query_consumer_build_bundle_summary,
    attach_omena_query_consumer_build_source_map_v3,
    attach_omena_query_consumer_build_source_map_v3_with_sources,
    attach_omena_query_consumer_build_source_map_v3_with_sources_and_resolution_inputs,
    collect_omena_query_style_cascade_narrowing_substrate,
    collect_omena_query_style_cascade_narrowing_substrate_with_external_sifs,
    execute_omena_query_consumer_build_style_source,
    execute_omena_query_consumer_build_style_source_for_target_query,
    execute_omena_query_consumer_build_style_source_for_target_query_with_context_and_options,
    execute_omena_query_consumer_build_style_source_for_target_query_with_options,
    execute_omena_query_consumer_build_style_source_with_context,
    execute_omena_query_consumer_build_style_source_with_engine_input_context,
    execute_omena_query_consumer_build_style_sources,
    execute_omena_query_consumer_build_style_sources_for_target_query_with_context_and_options,
    execute_omena_query_consumer_build_style_sources_for_target_query_with_context_and_options_and_resolution_inputs,
    execute_omena_query_consumer_build_style_sources_for_target_query_with_options,
    execute_omena_query_consumer_build_style_sources_with_context,
    execute_omena_query_consumer_build_style_sources_with_context_and_resolution_inputs,
    execute_omena_query_transform_passes_from_source,
    execute_omena_query_transform_passes_from_source_with_context,
    is_omena_query_sass_symbol_candidate_kind, is_omena_query_sass_symbol_declaration_kind,
    is_omena_query_sass_symbol_reference_kind, list_omena_query_transform_pass_summaries,
    occurrences_for_monikers, omena_query_sass_symbol_kind_from_candidate_kind,
    omena_query_sass_symbol_target_matches, omena_workspace_moniker,
    read_omena_query_cascade_at_position, read_omena_query_cascade_at_position_analysis_result,
    read_omena_query_cascade_at_position_from_graph,
    read_omena_query_cascade_at_position_with_categorical_evidence,
    read_omena_query_style_context_index, render_omena_query_css_module_typescript_declaration,
    render_omena_query_css_modules_interface_json, resolve_omena_query_sass_forward_sources,
    resolve_omena_query_sass_module_use_sources_for_candidate,
    resolve_omena_query_sass_symbol_declarations, resolve_omena_query_selector_rename_edits,
    resolve_omena_query_source_candidate_selector_names,
    resolve_omena_query_source_provider_candidates,
    resolve_omena_query_style_selector_definitions_for_source_candidate, run_omena_query_bundle,
    run_omena_query_bundle_for_style_sources_with_context,
    run_omena_query_bundle_with_semantic_inputs, summarize_omena_query_analyzed_graph,
    summarize_omena_query_bundle_code_split_source_map_v3,
    summarize_omena_query_bundle_code_split_workspace_plan, summarize_omena_query_bundle_evidence,
    summarize_omena_query_cascade_aware_style_diagnostics,
    summarize_omena_query_cascade_aware_style_diagnostics_with_deep_analysis,
    summarize_omena_query_cascade_site_outcomes_from_source,
    summarize_omena_query_categorical_design_system_cross_project_summary,
    summarize_omena_query_closed_world_outcome_for_style_source,
    summarize_omena_query_consumer_build_source_map_v3,
    summarize_omena_query_consumer_build_source_map_v3_with_resolution_inputs,
    summarize_omena_query_consumer_check_style_source,
    summarize_omena_query_css_modules_export_usage,
    summarize_omena_query_css_modules_interface_bundle,
    summarize_omena_query_css_modules_interface_summary_view,
    summarize_omena_query_css_modules_local_composes_style_diagnostics,
    summarize_omena_query_css_modules_resolution_style_diagnostics,
    summarize_omena_query_custom_property_annotations,
    summarize_omena_query_custom_property_occurrence_index,
    summarize_omena_query_dynamic_classname_m_tier_diagnostics_with_context_depth,
    summarize_omena_query_fast_facts, summarize_omena_query_global_class_fallthrough_diagnostic,
    summarize_omena_query_m4_axis_c_readiness,
    summarize_omena_query_missing_custom_property_diagnostics,
    summarize_omena_query_missing_extend_target_diagnostics,
    summarize_omena_query_missing_keyframes_diagnostics,
    summarize_omena_query_missing_sass_symbol_diagnostics,
    summarize_omena_query_missing_sass_symbol_diagnostics_for_workspace,
    summarize_omena_query_missing_selector_diagnostic,
    summarize_omena_query_module_interface_projection,
    summarize_omena_query_omena_parser_css_modules_intermediate,
    summarize_omena_query_omena_parser_lex, summarize_omena_query_omena_parser_style_facts,
    summarize_omena_query_refs_for_class,
    summarize_omena_query_refs_for_class_from_occurrence_index,
    summarize_omena_query_refs_for_workspace_class, summarize_omena_query_rename_plan,
    summarize_omena_query_rename_plan_for_workspace_class,
    summarize_omena_query_rename_plan_from_occurrence_index,
    summarize_omena_query_sass_import_deprecation_hints,
    summarize_omena_query_sass_module_cross_file_resolution_for_workspace,
    summarize_omena_query_sass_module_resolution_identity_diagnostics_for_workspace,
    summarize_omena_query_sass_module_sources,
    summarize_omena_query_source_baseline_diagnostics_for_workspace_file_with_source_syntax_index_and_definitions,
    summarize_omena_query_source_completion_at_position,
    summarize_omena_query_source_completion_for_workspace_file,
    summarize_omena_query_source_completion_for_workspace_file_with_resolution_inputs,
    summarize_omena_query_source_diagnostics_for_file,
    summarize_omena_query_source_diagnostics_for_workspace_file,
    summarize_omena_query_source_diagnostics_for_workspace_file_with_context_depth,
    summarize_omena_query_source_diagnostics_for_workspace_file_with_source_syntax_index,
    summarize_omena_query_source_diagnostics_for_workspace_file_with_source_syntax_index_and_context_depth,
    summarize_omena_query_source_diagnostics_for_workspace_file_with_source_syntax_index_and_definitions,
    summarize_omena_query_source_selector_occurrence_index,
    summarize_omena_query_source_selector_reference_cross_file_summary,
    summarize_omena_query_style_completion_at_position,
    summarize_omena_query_style_completion_candidate_documentation,
    summarize_omena_query_style_completion_candidate_documentation_for_workspace_file,
    summarize_omena_query_style_completion_candidate_documentation_for_workspace_file_with_substrate,
    summarize_omena_query_style_completion_for_workspace_file,
    summarize_omena_query_style_completion_for_workspace_file_with_resolution_inputs,
    summarize_omena_query_style_completion_for_workspace_file_with_substrate,
    summarize_omena_query_style_diagnostics_for_file,
    summarize_omena_query_style_diagnostics_for_file_with_deep_analysis,
    summarize_omena_query_style_diagnostics_for_file_with_local_composes,
    summarize_omena_query_style_diagnostics_for_file_with_local_composes_and_deep_analysis,
    summarize_omena_query_style_diagnostics_for_workspace_file,
    summarize_omena_query_style_diagnostics_for_workspace_file_with_external_mode,
    summarize_omena_query_style_diagnostics_for_workspace_file_with_external_mode_and_sifs,
    summarize_omena_query_style_diagnostics_for_workspace_file_with_external_mode_and_sifs_and_resolution_inputs,
    summarize_omena_query_style_diagnostics_for_workspace_file_with_external_mode_and_sifs_and_resolution_inputs_and_suppression_mode,
    summarize_omena_query_style_diagnostics_for_workspace_file_with_external_mode_and_sifs_and_suppression_mode,
    summarize_omena_query_style_document, summarize_omena_query_style_edit_distance,
    summarize_omena_query_style_edit_distance_cascade_margin_bridge,
    summarize_omena_query_style_extract_code_actions,
    summarize_omena_query_style_frame_refresh_facts_with_reuse,
    summarize_omena_query_style_hover_candidates, summarize_omena_query_style_hover_render_parts,
    summarize_omena_query_style_hover_render_parts_for_hover_position,
    summarize_omena_query_style_hover_render_parts_for_workspace_file,
    summarize_omena_query_style_hover_render_parts_for_workspace_file_hover_position,
    summarize_omena_query_style_hover_render_parts_for_workspace_file_hover_position_with_substrate,
    summarize_omena_query_style_hover_render_parts_for_workspace_file_with_substrate,
    summarize_omena_query_style_inline_code_actions,
    summarize_omena_query_style_insight_code_actions, summarize_omena_query_style_insights,
    summarize_omena_query_style_refactor_code_actions,
    summarize_omena_query_style_semantic_graph_batch_from_sources,
    summarize_omena_query_style_semantic_graph_batch_from_sources_with_package_manifests,
    summarize_omena_query_style_semantic_graph_from_source,
    summarize_omena_query_target_unresolved_sass_import_diagnostics_for_workspace_paths,
    summarize_omena_query_transform_context_from_engine_input,
    summarize_omena_query_transform_context_from_sources,
    summarize_omena_query_transform_context_from_sources_with_resolution_inputs,
    summarize_omena_query_transform_plan_from_source,
    summarize_omena_query_transform_plan_from_source_with_context,
    summarize_omena_query_transform_plan_from_target_query,
    summarize_omena_query_transform_plan_from_target_query_with_context,
    summarize_omena_query_unused_selector_style_diagnostics,
    summarize_omena_query_unused_selector_style_diagnostics_with_path_mappings,
    summarize_omena_query_workspace_cross_file_summary,
    summarize_omena_query_workspace_occurrence_index_from_occurrences,
    summarize_omena_query_workspace_occurrence_index_from_source_occurrences,
    validate_omena_query_closed_world_decision_parity,
};
#[cfg(feature = "salsa-memo")]
pub use style::{
    OmenaQueryCommittedStyleSemanticGraphV0, OmenaQueryCommittedWaveSubstrateV0,
    OmenaQueryStyleDiagnosticsWithSelectorV0, OmenaQueryStyleFileInputV0,
    OmenaQueryStyleMemoDatabaseV0, OmenaQueryStyleMemoHostV0, OmenaQueryStyleParallelResolveSyncV0,
    OmenaQueryStyleRevisionSelectorV0, OmenaQueryStyleWorkspaceInputV0,
    OmenaQueryStyleWorkspaceTransactionCommitV0, OmenaQueryStyleWorkspaceTransactionErrorV0,
    OmenaQueryStyleWorkspaceTransactionV0,
    memo_css_modules_cross_file_resolution_from_module_interfaces,
    memo_module_interface_projection,
    memo_sass_module_cross_file_resolution_from_module_interfaces,
    memo_sass_module_cross_file_resolution_with_external_sifs_from_module_interfaces,
    memo_sass_module_cross_file_resolution_without_manifests_from_module_interfaces,
    memo_sass_module_cross_file_resolution_without_path_mappings_from_module_interfaces,
    prepare_committed_workspace_wave_substrate,
    resolve_committed_workspace_style_diagnostics_from_view,
    resolve_committed_workspace_style_diagnostics_from_view_with_external_mode,
    resolve_committed_workspace_style_diagnostics_from_view_with_external_mode_and_suppression_mode,
    resolve_committed_workspace_style_diagnostics_from_view_with_identity_index,
    resolve_committed_workspace_style_diagnostics_from_view_with_identity_index_and_wave_substrate,
};
#[cfg(all(feature = "salsa-memo", any(test, feature = "test-support")))]
pub use style::{
    read_committed_style_semantic_graph_compute_count_for_test,
    read_css_modules_cross_file_resolution_compute_count_for_test,
    read_css_modules_import_edge_resolution_probe_for_test,
    read_sass_module_edge_resolution_probe_for_test,
    reset_committed_style_semantic_graph_compute_count_for_test,
    reset_css_modules_cross_file_resolution_compute_count_for_test,
    reset_css_modules_import_edge_resolution_probe_for_test,
    reset_sass_module_edge_resolution_probe_for_test,
};
#[cfg(all(feature = "salsa-memo", feature = "test-support"))]
pub use style::{
    read_module_interface_projection_probe_for_test, read_style_fact_entry_probe_for_test,
    reset_module_interface_projection_probe_for_test, reset_style_fact_entry_probe_for_test,
};
#[cfg(any(test, feature = "test-support"))]
pub use style::{
    read_sass_module_resolution_direct_recompute_count_for_test,
    read_sass_module_resolution_internal_compute_count_for_test,
    read_workspace_cross_file_summary_direct_recompute_count_for_test,
    read_workspace_cross_file_summary_internal_compute_count_for_test,
    reset_sass_module_resolution_direct_recompute_count_for_test,
    reset_sass_module_resolution_internal_compute_count_for_test,
    reset_workspace_cross_file_summary_direct_recompute_count_for_test,
    reset_workspace_cross_file_summary_internal_compute_count_for_test,
};
#[cfg(feature = "lawvere-trace")]
pub use types::OmenaQueryLawvereTransformExecuteSummaryV0;
pub use types::{
    AnalyzedGraphV0, CanonicalFormV0, DesignSystemMinimumDescriptionV0, FastFactsV0, ModelClassV0,
    OmenaQueryBoundarySummaryV0, OmenaQueryBundleArtifactV0,
    OmenaQueryBundleCodeSplitWorkspacePlanOutputV0, OmenaQueryBundleCodeSplitWorkspacePlanV0,
    OmenaQueryBundleEvidenceGateV0, OmenaQueryBundleEvidenceManifestV0,
    OmenaQueryBundleReachabilityEvidenceV0, OmenaQueryBundleResultV0,
    OmenaQueryCascadeAtPositionV0, OmenaQueryCascadeConfidenceV0, OmenaQueryCascadeInsightV0,
    OmenaQueryCascadeNarrowingEvidenceV0, OmenaQueryCategoricalDesignSystemCrossProjectSummaryV0,
    OmenaQueryClosedWorldBlockerV0, OmenaQueryClosedWorldDecisionParityV0,
    OmenaQueryClosedWorldOutcomeV0, OmenaQueryCodeActionPlanV0, OmenaQueryCodeActionV0,
    OmenaQueryCompletionAtPositionV0, OmenaQueryCompletionCandidateV0, OmenaQueryCompletionItemV0,
    OmenaQueryConsumerBuildSummaryV0, OmenaQueryConsumerCheckSummaryV0,
    OmenaQueryCreateCustomPropertyActionV0, OmenaQueryCreateSelectorActionV0,
    OmenaQueryCssModuleComposesEdgeFactV0, OmenaQueryCssModuleValueDefinitionEdgeFactV0,
    OmenaQueryCssModuleValueImportEdgeFactV0, OmenaQueryCssModulesComposesClosureEdgeV0,
    OmenaQueryCssModulesCrossFileResolutionCapabilitiesV0,
    OmenaQueryCssModulesCrossFileResolutionV0, OmenaQueryCssModulesCycleV0,
    OmenaQueryCssModulesIcssClosureEdgeV0, OmenaQueryCssModulesImportEdgeResolutionV0,
    OmenaQueryCssModulesValueClosureEdgeV0, OmenaQueryCustomPropertyAnnotationSummaryV0,
    OmenaQueryCustomPropertyAnnotationV0, OmenaQueryCustomPropertyOccurrenceIndexV0,
    OmenaQueryCustomPropertyOccurrenceV0, OmenaQueryDiagnosticSuppressionModeV0,
    OmenaQueryDiagnosticSuppressionReasonV0, OmenaQueryDiagnosticSuppressionSummaryV0,
    OmenaQueryEvaluationRuntimeSummaryV0, OmenaQueryExternalSifInputV0,
    OmenaQueryIcssExportEdgeFactV0, OmenaQueryIcssImportEdgeFactV0,
    OmenaQueryInlineStyleRuntimeOverrideV0, OmenaQueryInsightV0, OmenaQueryLinearProvenanceV0,
    OmenaQueryM4AxisCReadinessSummaryV0, OmenaQueryM4AxisCSummaryHashSamplesV0,
    OmenaQueryOmenaParserStyleFactsV0, OmenaQueryPolynomialProvenanceV0,
    OmenaQueryReferenceLocationV0, OmenaQueryRefsForClassV0, OmenaQueryRenamePlanV0,
    OmenaQueryRuntimeStateDriverSummaryV0, OmenaQueryRuntimeStateScenarioEvidenceV0,
    OmenaQueryRuntimeStateScenarioV0, OmenaQueryRuntimeStateStaticBoundaryV0,
    OmenaQuerySassModuleConformanceReportV0, OmenaQuerySassModuleConformanceRowV0,
    OmenaQuerySassModuleCrossFileResolutionCapabilitiesV0,
    OmenaQuerySassModuleCrossFileResolutionV0, OmenaQuerySassModuleCycleV0,
    OmenaQuerySassModuleEdgeFactV0, OmenaQuerySassModuleEdgeResolutionV0,
    OmenaQuerySassModuleGraphClosureEdgeV0, OmenaQuerySassModuleSourcesV0,
    OmenaQuerySassModuleUseEdgeV0, OmenaQuerySassSymbolFactV0,
    OmenaQuerySassSymbolResolutionCapabilitiesV0, OmenaQuerySassSymbolResolutionEdgeV0,
    OmenaQuerySassSymbolResolutionV0, OmenaQuerySchemaVersionCheckV0,
    OmenaQuerySchemaVersionPolicyV0, OmenaQuerySemanticReachabilitySourceV0,
    OmenaQueryShorthandCombinableV0, OmenaQuerySourceDiagnosticV0,
    OmenaQuerySourceDiagnosticsForFileV0, OmenaQuerySourceDocumentInputV0,
    OmenaQuerySourceMissingSelectorDiagnosticCandidateV0,
    OmenaQuerySourceProviderCandidateResolutionV0, OmenaQuerySourceSelectorCandidateV0,
    OmenaQuerySourceSelectorOccurrenceIndexV0, OmenaQuerySourceSelectorOccurrenceV0,
    OmenaQuerySourceSelectorReferenceCandidateV0, OmenaQuerySourceSelectorReferenceEditTargetV0,
    OmenaQueryStaticConditionPruningEvidenceV0, OmenaQueryStyleCompletionConsumerDecisionV0,
    OmenaQueryStyleContextIndexV0, OmenaQueryStyleDiagnosticV0,
    OmenaQueryStyleDiagnosticsForFileV0, OmenaQueryStyleDocumentSummaryV0,
    OmenaQueryStyleHoverCandidateV0, OmenaQueryStyleHoverCandidatesV0,
    OmenaQueryStyleHoverRenderPartsV0, OmenaQueryStyleInsightsV0, OmenaQueryStylePackageManifestV0,
    OmenaQueryStyleSelectorDefinitionV0, OmenaQueryStyleSemanticGraphBatchEntryV0,
    OmenaQueryStyleSemanticGraphBatchOutputV0, OmenaQueryStyleSourceInputV0,
    OmenaQuerySymlinkChainLinkV0, OmenaQueryTransformContextFromEngineInputSummaryV0,
    OmenaQueryTransformContextFromSourcesSummaryV0, OmenaQueryTransformExecuteSummaryV0,
    OmenaQueryTransformPassSummaryV0, OmenaQueryTransformPlanSummaryV0,
    OmenaQueryWorkspaceTextEditV0, OmenaWorkspaceOccurrenceFamilyV0,
    OmenaWorkspaceOccurrenceIndexV0, OmenaWorkspaceOccurrenceKindV0,
    OmenaWorkspaceOccurrenceRoleV0, OmenaWorkspaceOccurrenceSurfaceV0, OmenaWorkspaceOccurrenceV0,
    SassNamespaceBitsV0, SelectedQueryAdapterCapabilitiesV0, SelectedQueryBackendCapabilityV0,
    SelectedQueryRunnerCommandV0, SourcePinV0, StyleEditDistanceCascadeMarginBridgeV0,
    StyleEditDistanceSummaryV0, fact_precision_from_evidence_analysis_precision,
    round_trip_omena_query_linear_provenance_labels, summarize_omena_query_linear_provenance,
    summarize_omena_query_linear_provenance_semiring_laws,
    summarize_omena_query_linear_provenance_with_support_count,
    summarize_omena_query_polynomial_provenance,
};
pub(crate) use types::{
    OMENA_QUERY_TSGO_PROVIDER_UNAVAILABLE_PROVENANCE, OMENA_QUERY_TYPE_ORACLE_UNKNOWN_VALUE_DOMAIN,
    apply_omena_query_checker_product_gate_to_source_diagnostics,
    apply_omena_query_checker_product_gate_to_style_diagnostics, source_diagnostic_precision,
};
