// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-sdk-workflow/main.tsp.
// Do not edit this file by hand.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum OmenaSdkResponsePartitionV0 {
    Public,
    Debug,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum OmenaErrorClassV0 {
    Input,
    Workspace,
    Resolution,
    Analysis,
    Transform,
    Unsupported,
    Internal,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum OmenaErrorSeverityV0 {
    Error,
    Warning,
    Information,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OmenaErrorRecoverabilityV0 {
    #[serde(rename = "retry")]
    Retry,
    #[serde(rename = "user-action")]
    UserAction,
    #[serde(rename = "not-recoverable")]
    NotRecoverable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaErrorEvidenceReferenceV0 {
    pub query_identity: String,
    pub input_identity: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaErrorContextV0 {
    pub code: String,
    pub severity: OmenaErrorSeverityV0,
    pub recoverability: OmenaErrorRecoverabilityV0,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub evidence: Vec<OmenaErrorEvidenceReferenceV0>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaErrorV0 {
    pub class: OmenaErrorClassV0,
    pub message: String,
    pub context: OmenaErrorContextV0,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkErrorEnvelopeV0 {
    pub error: OmenaErrorV0,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaCliResponseEnvelopeV0 {
    pub schema_version: String,
    pub product: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub config_content_digest: Option<String>,
    pub payload: serde_json::Value,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkSnapshotRequestV0 {
    pub workspace_root: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkSnapshotResponseV0 {
    pub snapshot_id: crate::OmenaWorkspaceSnapshotIdV0,
    pub partition: OmenaSdkResponsePartitionV0,
    pub workspace_root: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkQueryRequestV0 {
    pub snapshot_id: crate::OmenaWorkspaceSnapshotIdV0,
    pub query_kind: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkQueryResponseV0 {
    pub snapshot_id: crate::OmenaWorkspaceSnapshotIdV0,
    pub partition: OmenaSdkResponsePartitionV0,
    pub payload: serde_json::Value,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkDiagnosticsRequestV0 {
    pub snapshot_id: crate::OmenaWorkspaceSnapshotIdV0,
    pub style_path: String,
    pub style_source: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkDiagnosticsSummaryV0 {
    pub schema_version: String,
    pub product: String,
    pub style_path: String,
    pub dialect: String,
    pub token_count: u64,
    pub parser_error_count: u64,
    pub class_selector_count: u64,
    pub custom_property_count: u64,
    pub keyframe_count: u64,
    pub ready_surfaces: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkDiagnosticsResponseV0 {
    pub snapshot_id: crate::OmenaWorkspaceSnapshotIdV0,
    pub partition: OmenaSdkResponsePartitionV0,
    pub summary: OmenaSdkDiagnosticsSummaryV0,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkDiagnosticsDebugReportV0 {
    pub snapshot_id: crate::OmenaWorkspaceSnapshotIdV0,
    pub partition: OmenaSdkResponsePartitionV0,
    pub public_response: OmenaSdkDiagnosticsResponseV0,
    pub analysis: serde_json::Value,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkBuildRequestV0 {
    pub snapshot_id: crate::OmenaWorkspaceSnapshotIdV0,
    pub style_path: String,
    pub style_source: String,
    pub pass_ids: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<crate::OmenaQueryTransformExecutionContextV0>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkBuildResponseV0 {
    pub snapshot_id: crate::OmenaWorkspaceSnapshotIdV0,
    pub partition: OmenaSdkResponsePartitionV0,
    pub summary: serde_json::Value,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkExplainPositionV0 {
    pub line: i32,
    pub character: i32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkExplainRequestV0 {
    pub snapshot_id: crate::OmenaWorkspaceSnapshotIdV0,
    pub style_path: String,
    pub position: OmenaSdkExplainPositionV0,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OmenaSdkExplainResponseV0 {
    pub snapshot_id: crate::OmenaWorkspaceSnapshotIdV0,
    pub partition: OmenaSdkResponsePartitionV0,
    pub report: serde_json::Value,
}
