/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-v2/main.tsp.
// Do not edit this file by hand.

export type CodeActionPlanKindJson = "quickfix" | "refactor.extract" | "refactor.inline";

export interface OmenaQueryCodeActionPlanV0Json {
  schemaVersion: string;
  product: "omena-query.code-actions";
  fileUri: string;
  fileKind: "style";
  actionCount: number;
  actions: OmenaQueryCodeActionV0Json[];
  readySurfaces?: string[];
}
export interface OmenaQueryCodeActionV0Json {
  title: string;
  kind: CodeActionPlanKindJson;
  edits: OmenaQueryWorkspaceTextEditV0Json[];
  source: string;
}
export interface OmenaQueryWorkspaceTextEditV0Json {
  uri: string;
  range: unknown;
  newText: string;
}
