/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-v2/main.tsp.
// Do not edit this file by hand.

export type CodeActionPlanKindJson = "quickfix" | "refactor.extract" | "refactor.inline";

export interface OmenaQueryCodeActionPlanV0Json {
  readonly schemaVersion: string;
  readonly product: "omena-query.code-actions";
  readonly fileUri: string;
  readonly fileKind: "style";
  readonly actionCount: number;
  readonly actions: readonly OmenaQueryCodeActionV0Json[];
  readonly readySurfaces?: readonly string[];
}
export interface OmenaQueryCodeActionV0Json {
  readonly title: string;
  readonly kind: CodeActionPlanKindJson;
  readonly edits: readonly OmenaQueryWorkspaceTextEditV0Json[];
  readonly source: string;
}
export interface OmenaQueryWorkspaceTextEditV0Json {
  readonly uri: string;
  readonly range: unknown;
  readonly newText: string;
}
