/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-v2/main.tsp.
// Do not edit this file by hand.

export type {
  EngineOutputV2Json as HostEngineOutputV2Json,
  QueryResultV2Json as HostQueryResultV2Json,
  ExpressionSemanticsQueryResultV2Json as HostExpressionSemanticsQueryResultV2Json,
  SourceExpressionResolutionQueryResultV2Json as HostSourceExpressionResolutionQueryResultV2Json,
  SelectorUsageQueryResultV2Json as HostSelectorUsageQueryResultV2Json,
} from "../../engine-core-ts/src/contracts/engine-v2-output-idl.generated";
