/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-v2/main.tsp.
// Do not edit this file by hand.

export type {
  QueryResultV2Json as EngineQueryResultV2Json,
  ExpressionSemanticsQueryResultV2Json,
  SourceExpressionResolutionQueryResultV2Json,
  SelectorUsageQueryResultV2Json,
} from "../../engine-core-ts/src/contracts/engine-v2-output-idl.generated";
