/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-v2/main.tsp.
// Do not edit this file by hand.

export type OmenaQueryDiagnosticsForFileV0Json =
  | OmenaQuerySourceDiagnosticsForFileV0Json
  | OmenaQueryStyleDiagnosticsForFileV0Json;
export type OmenaQueryDiagnosticSeverityV0Json = "error" | "warning" | "information" | "hint";
export type OmenaQueryValueDomainPrecisionV1Json =
  | "exactClassValue"
  | "closedClassValueSet"
  | "patternClassValue"
  | "cascadeAtPosition"
  | "styleModuleResolution"
  | "classValueResolution"
  | "classValueUniverse"
  | "classValueFlow"
  | "unknown";
export type OmenaQueryFlowPrecisionV1Json =
  | "representationBound"
  | "providerObservation"
  | "incrementalDataflow"
  | "positionScopedCascade"
  | "sourceSelectorUsage"
  | "sourceControlFlow"
  | "sourceSyntaxIndex"
  | "globalClassUniverse"
  | "sourceImportResolution"
  | "typeOracleProviderUnavailable"
  | "sourceDomainReference"
  | "sourceSelectorReference"
  | "kLimitedCallSiteFlow"
  | "fixture"
  | "unknown";
export type OmenaQueryContextPrecisionV1Json =
  | "valueLocal"
  | "providerScoped"
  | "perExpressionGraph"
  | "styleSemanticGraph"
  | "perModuleExport"
  | "sameFile"
  | "perSourceReference"
  | "perImportSpecifier"
  | "perTypeFactTarget"
  | "perDomainAxis"
  | "resolvedClassValueDomain"
  | "0-cfa"
  | "1-cfa"
  | "k-cfa"
  | "fixture"
  | "unknown";
export type OmenaQueryProviderCompletenessV1Json =
  | "complete"
  | "partial"
  | "unresolved"
  | "unknown";
export type OmenaQueryWorldAssumptionV1Json = "closed" | "open" | "unknown";
export type OmenaQueryRevisionIdentityV1Json =
  | "OmenaQuerySourceDiagnosticsForFileV0.input"
  | "OmenaQueryExpressionDomainFlowRuntimeV0.revision"
  | "OmenaQueryEvaluationRuntimeSummaryV0.expressionDomainRevision"
  | "workspaceSnapshot"
  | "current"
  | "staleTypeFact"
  | "unknown";

export interface OmenaQuerySourceDiagnosticsForFileV0Json {
  readonly schemaVersion: string;
  readonly product: "omena-query.diagnostics-for-file";
  readonly fileUri: string;
  readonly fileKind: "source";
  readonly diagnosticCount: number;
  readonly diagnostics: readonly OmenaQuerySourceDiagnosticV0Json[];
  readonly readySurfaces: readonly string[];
}
export interface OmenaQuerySourceDiagnosticV0Json {
  readonly code: string;
  readonly severity: OmenaQueryDiagnosticSeverityV0Json;
  readonly provenance: readonly string[];
  readonly range: TextRangeJsonV2Json;
  readonly message: string;
  readonly precision?: OmenaQueryAnalysisPrecisionV0Json;
  readonly suggestion?: string;
  readonly createSelector?: OmenaQueryCreateSelectorActionV0Json;
}
export interface TextRangeJsonV2Json {
  readonly start: TextPositionJsonV2Json;
  readonly end: TextPositionJsonV2Json;
}
export interface TextPositionJsonV2Json {
  readonly line: number;
  readonly character: number;
}
export interface OmenaQueryAnalysisPrecisionV0Json {
  readonly product: string;
  readonly valueDomain: OmenaQueryValueDomainPrecisionV1Json;
  readonly flowSensitivity: OmenaQueryFlowPrecisionV1Json;
  readonly contextSensitivity: OmenaQueryContextPrecisionV1Json;
  readonly providerCompleteness: OmenaQueryProviderCompletenessV1Json;
  readonly worldAssumption: OmenaQueryWorldAssumptionV1Json;
  readonly revisionAxis: OmenaQueryRevisionIdentityV1Json;
}
export interface OmenaQueryCreateSelectorActionV0Json {
  readonly uri: string;
  readonly range: TextRangeJsonV2Json;
  readonly newText: string;
  readonly selectorName: string;
}
export interface OmenaQueryStyleDiagnosticsForFileV0Json {
  readonly schemaVersion: string;
  readonly product: "omena-query.diagnostics-for-file";
  readonly fileUri: string;
  readonly fileKind: "style";
  readonly diagnosticCount: number;
  readonly diagnostics: readonly OmenaQueryStyleDiagnosticV0Json[];
  readonly readySurfaces: readonly string[];
  readonly suppressionSummary?: unknown;
}
export interface OmenaQueryStyleDiagnosticV0Json {
  readonly code: string;
  readonly severity: OmenaQueryDiagnosticSeverityV0Json;
  readonly provenance: readonly string[];
  readonly range: TextRangeJsonV2Json;
  readonly message: string;
  readonly tags?: readonly number[];
  readonly createModuleFile?: OmenaQueryCreateModuleFileActionV0Json;
  readonly createSelector?: OmenaQueryCreateSelectorActionV0Json;
  readonly createValue?: OmenaQueryCreateValueActionV0Json;
  readonly createKeyframes?: OmenaQueryCreateKeyframesActionV0Json;
  readonly createCustomProperty?: OmenaQueryCreateCustomPropertyActionV0Json;
  readonly createSassSymbol?: OmenaQueryCreateSassSymbolActionV0Json;
  readonly cascadeNarrowing?: unknown;
  readonly cascadeConfidence?: unknown;
  readonly polynomialProvenance?: unknown;
  readonly crossFileScc?: unknown;
}
export interface OmenaQueryCreateModuleFileActionV0Json {
  readonly uri: string;
}
export interface OmenaQueryCreateValueActionV0Json {
  readonly uri: string;
  readonly range: TextRangeJsonV2Json;
  readonly newText: string;
  readonly valueName: string;
}
export interface OmenaQueryCreateKeyframesActionV0Json {
  readonly uri: string;
  readonly range: TextRangeJsonV2Json;
  readonly newText: string;
  readonly animationName: string;
}
export interface OmenaQueryCreateCustomPropertyActionV0Json {
  readonly uri: string;
  readonly range: TextRangeJsonV2Json;
  readonly newText: string;
  readonly propertyName: string;
}
export interface OmenaQueryCreateSassSymbolActionV0Json {
  readonly uri: string;
  readonly range: TextRangeJsonV2Json;
  readonly newText: string;
  readonly symbolKind: string;
  readonly symbolName: string;
  readonly symbolSyntax: string;
}
