/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-v2/main.tsp.
// Do not edit this file by hand.

export type OmenaQueryDiagnosticsForFileV0Json =
  | OmenaQuerySourceDiagnosticsForFileV0Json
  | OmenaQueryStyleDiagnosticsForFileV0Json;
export type OmenaQueryDiagnosticSeverityV0Json = "error" | "warning" | "information" | "hint";

export interface OmenaQuerySourceDiagnosticsForFileV0Json {
  readonly schemaVersion: string;
  readonly product: "omena-query.diagnostics-for-file";
  readonly fileUri: string;
  readonly fileKind: "source";
  readonly diagnosticCount: number;
  readonly diagnostics: readonly OmenaQuerySourceDiagnosticV0Json[];
  readonly readySurfaces: readonly string[];
}
export interface OmenaQuerySourceDiagnosticV0Json {
  readonly code: string;
  readonly severity: OmenaQueryDiagnosticSeverityV0Json;
  readonly provenance: readonly string[];
  readonly range: TextRangeJsonV2Json;
  readonly message: string;
  readonly precision?: OmenaQueryAnalysisPrecisionV0Json;
  readonly suggestion?: string;
  readonly createSelector?: OmenaQueryCreateSelectorActionV0Json;
}
export interface TextRangeJsonV2Json {
  readonly start: TextPositionJsonV2Json;
  readonly end: TextPositionJsonV2Json;
}
export interface TextPositionJsonV2Json {
  readonly line: number;
  readonly character: number;
}
export interface OmenaQueryAnalysisPrecisionV0Json {
  readonly product: string;
  readonly valueDomain: string;
  readonly flowSensitivity: string;
  readonly contextSensitivity: string;
  readonly revisionAxis: string;
}
export interface OmenaQueryCreateSelectorActionV0Json {
  readonly uri: string;
  readonly range: TextRangeJsonV2Json;
  readonly newText: string;
  readonly selectorName: string;
}
export interface OmenaQueryStyleDiagnosticsForFileV0Json {
  readonly schemaVersion: string;
  readonly product: "omena-query.diagnostics-for-file";
  readonly fileUri: string;
  readonly fileKind: "style";
  readonly diagnosticCount: number;
  readonly diagnostics: readonly OmenaQueryStyleDiagnosticV0Json[];
  readonly readySurfaces: readonly string[];
  readonly suppressionSummary?: unknown;
}
export interface OmenaQueryStyleDiagnosticV0Json {
  readonly code: string;
  readonly severity: OmenaQueryDiagnosticSeverityV0Json;
  readonly provenance: readonly string[];
  readonly range: TextRangeJsonV2Json;
  readonly message: string;
  readonly tags?: readonly number[];
  readonly createModuleFile?: OmenaQueryCreateModuleFileActionV0Json;
  readonly createSelector?: OmenaQueryCreateSelectorActionV0Json;
  readonly createValue?: OmenaQueryCreateValueActionV0Json;
  readonly createKeyframes?: OmenaQueryCreateKeyframesActionV0Json;
  readonly createCustomProperty?: OmenaQueryCreateCustomPropertyActionV0Json;
  readonly createSassSymbol?: OmenaQueryCreateSassSymbolActionV0Json;
  readonly cascadeNarrowing?: unknown;
  readonly cascadeConfidence?: unknown;
  readonly polynomialProvenance?: unknown;
  readonly crossFileScc?: unknown;
}
export interface OmenaQueryCreateModuleFileActionV0Json {
  readonly uri: string;
}
export interface OmenaQueryCreateValueActionV0Json {
  readonly uri: string;
  readonly range: TextRangeJsonV2Json;
  readonly newText: string;
  readonly valueName: string;
}
export interface OmenaQueryCreateKeyframesActionV0Json {
  readonly uri: string;
  readonly range: TextRangeJsonV2Json;
  readonly newText: string;
  readonly animationName: string;
}
export interface OmenaQueryCreateCustomPropertyActionV0Json {
  readonly uri: string;
  readonly range: TextRangeJsonV2Json;
  readonly newText: string;
  readonly propertyName: string;
}
export interface OmenaQueryCreateSassSymbolActionV0Json {
  readonly uri: string;
  readonly range: TextRangeJsonV2Json;
  readonly newText: string;
  readonly symbolKind: string;
  readonly symbolName: string;
  readonly symbolSyntax: string;
}
