/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-v2/main.tsp.
// Do not edit this file by hand.

export type QueryResultV2Json =
  | ExpressionSemanticsQueryResultV2Json
  | SourceExpressionResolutionQueryResultV2Json
  | SelectorUsageQueryResultV2Json;
export type ValueDomainKindV2Json = "none" | "exact" | "finiteSet" | "constrained" | "top";
export type StringConstraintKindV2Json =
  | "prefix"
  | "suffix"
  | "prefixSuffix"
  | "charInclusion"
  | "composite";
export type CertaintyShapeKindV2Json = "exact" | "boundedFinite" | "constrained" | "unknown";

export interface EngineOutputV2Json {
  readonly version: "2";
  readonly queryResults: readonly QueryResultV2Json[];
  readonly rewritePlans: readonly TextRewritePlanJsonV2Json[];
  readonly checkerReport: CheckerReportJsonV1Json;
}
export interface ExpressionSemanticsQueryResultV2Json {
  readonly kind: "expression-semantics";
  readonly filePath: string;
  readonly queryId: string;
  readonly payload: ExpressionSemanticsPayloadV2Json;
}
export interface ExpressionSemanticsPayloadV2Json {
  readonly expressionId: string;
  readonly expressionKind: string;
  readonly styleFilePath: string | null;
  readonly selectorNames: readonly string[];
  readonly candidateNames: readonly string[];
  readonly finiteValues: readonly string[] | null;
  readonly valueDomainKind: ValueDomainKindV2Json;
  readonly valueConstraintKind?: StringConstraintKindV2Json;
  readonly valuePrefix?: string;
  readonly valueSuffix?: string;
  readonly valueMinLen?: number;
  readonly valueMaxLen?: number;
  readonly valueCharMust?: string;
  readonly valueCharMay?: string;
  readonly valueMayIncludeOtherChars?: boolean;
  readonly valueDomainReason?: string;
  readonly valueDomainDerivation?: ValueDomainDerivationV2Json;
  readonly valueDomainProvenanceTree?: ValueDomainProvenanceTreeV2Json;
  readonly selectorCertainty: string;
  readonly selectorCertaintyShapeKind?: CertaintyShapeKindV2Json;
  readonly selectorConstraintKind?: StringConstraintKindV2Json;
  readonly selectorCertaintyShapeLabel?: string;
  readonly selectorCertaintyReason?: string;
  readonly valueCertainty?: string;
  readonly valueCertaintyShapeKind?: CertaintyShapeKindV2Json;
  readonly valueCertaintyConstraintKind?: StringConstraintKindV2Json;
  readonly valueCertaintyShapeLabel?: string;
  readonly valueCertaintyReason?: string;
  readonly reason?: string;
}
export interface ValueDomainDerivationV2Json {
  readonly schemaVersion: string;
  readonly product: string;
  readonly inputFactKind: string;
  readonly inputConstraintKind?: string;
  readonly inputValueCount: number;
  readonly reducedKind: string;
  readonly steps: readonly ValueDomainDerivationStepV2Json[];
}
export interface ValueDomainDerivationStepV2Json {
  readonly operation: string;
  readonly inputKind?: string;
  readonly refinementKind?: string;
  readonly resultKind: string;
  readonly resultProvenance?: string;
  readonly reason: string;
}
export interface ValueDomainProvenanceTreeV2Json {
  readonly schemaVersion: string;
  readonly product: string;
  readonly valueKind: string;
  readonly value: unknown;
  readonly valueProvenance?: string;
  readonly root: ValueDomainProvenanceNodeV2Json;
}
export interface ValueDomainProvenanceNodeV2Json {
  readonly operation: string;
  readonly resultKind: string;
  readonly resultProvenance?: string;
  readonly detail?: string;
  readonly reason: string;
  readonly children: readonly ValueDomainProvenanceNodeV2Json[];
}
export interface SourceExpressionResolutionQueryResultV2Json {
  readonly kind: "source-expression-resolution";
  readonly filePath: string;
  readonly queryId: string;
  readonly payload: SourceExpressionResolutionPayloadV2Json;
}
export interface SourceExpressionResolutionPayloadV2Json {
  readonly expressionId: string;
  readonly styleFilePath: string | null;
  readonly selectorNames: readonly string[];
  readonly finiteValues: readonly string[] | null;
  readonly selectorCertainty: string;
  readonly selectorCertaintyShapeKind?: CertaintyShapeKindV2Json;
  readonly selectorConstraintKind?: StringConstraintKindV2Json;
  readonly selectorCertaintyShapeLabel?: string;
  readonly selectorCertaintyReason?: string;
  readonly valueCertainty?: string;
  readonly valueCertaintyShapeKind?: CertaintyShapeKindV2Json;
  readonly valueCertaintyConstraintKind?: StringConstraintKindV2Json;
  readonly valuePrefix?: string;
  readonly valueSuffix?: string;
  readonly valueMinLen?: number;
  readonly valueMaxLen?: number;
  readonly valueCharMust?: string;
  readonly valueCharMay?: string;
  readonly valueMayIncludeOtherChars?: boolean;
  readonly valueCertaintyShapeLabel?: string;
  readonly valueCertaintyReason?: string;
  readonly reason?: string;
}
export interface SelectorUsageQueryResultV2Json {
  readonly kind: "selector-usage";
  readonly filePath: string;
  readonly queryId: string;
  readonly payload: SelectorUsagePayloadV2Json;
}
export interface SelectorUsagePayloadV2Json {
  readonly canonicalName: string;
  readonly totalReferences: number;
  readonly directReferenceCount: number;
  readonly editableDirectReferenceCount: number;
  readonly exactReferenceCount: number;
  readonly inferredOrBetterReferenceCount: number;
  readonly hasExpandedReferences: boolean;
  readonly hasStyleDependencyReferences: boolean;
  readonly hasAnyReferences: boolean;
}
export interface TextRewritePlanJsonV2Json {
  readonly target: unknown;
  readonly edits: readonly PlannedTextEditJsonV2Json[];
}
export interface PlannedTextEditJsonV2Json {
  readonly uri: string;
  readonly range: TextRangeJsonV2Json;
  readonly newText: string;
}
export interface TextRangeJsonV2Json {
  readonly start: TextPositionJsonV2Json;
  readonly end: TextPositionJsonV2Json;
}
export interface TextPositionJsonV2Json {
  readonly line: number;
  readonly character: number;
}
export interface CheckerReportJsonV1Json {
  readonly version: string;
  readonly findings: readonly unknown[];
  readonly summary: unknown;
}
