/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-v2/main.tsp.
// Do not edit this file by hand.

export type QueryResultV2Json =
  | ExpressionSemanticsQueryResultV2Json
  | SourceExpressionResolutionQueryResultV2Json
  | SelectorUsageQueryResultV2Json;
export type ValueDomainKindV2Json = "none" | "exact" | "finiteSet" | "constrained" | "top";
export type StringConstraintKindV2Json =
  | "prefix"
  | "suffix"
  | "prefixSuffix"
  | "charInclusion"
  | "composite";
export type CertaintyShapeKindV2Json = "exact" | "boundedFinite" | "constrained" | "unknown";

export interface EngineOutputV2Json {
  version: "2";
  queryResults: QueryResultV2Json[];
  rewritePlans: TextRewritePlanJsonV2Json[];
  checkerReport: CheckerReportJsonV1Json;
}
export interface ExpressionSemanticsQueryResultV2Json {
  kind: "expression-semantics";
  filePath: string;
  queryId: string;
  payload: ExpressionSemanticsPayloadV2Json;
}
export interface ExpressionSemanticsPayloadV2Json {
  expressionId: string;
  expressionKind: string;
  styleFilePath: string | null;
  selectorNames: string[];
  candidateNames: string[];
  finiteValues: string[] | null;
  valueDomainKind: ValueDomainKindV2Json;
  valueConstraintKind?: StringConstraintKindV2Json;
  valuePrefix?: string;
  valueSuffix?: string;
  valueMinLen?: number;
  valueMaxLen?: number;
  valueCharMust?: string;
  valueCharMay?: string;
  valueMayIncludeOtherChars?: boolean;
  valueDomainReason?: string;
  valueDomainDerivation?: ValueDomainDerivationV2Json;
  valueDomainProvenanceTree?: ValueDomainProvenanceTreeV2Json;
  selectorCertainty: string;
  selectorCertaintyShapeKind?: CertaintyShapeKindV2Json;
  selectorConstraintKind?: StringConstraintKindV2Json;
  selectorCertaintyShapeLabel?: string;
  selectorCertaintyReason?: string;
  valueCertainty?: string;
  valueCertaintyShapeKind?: CertaintyShapeKindV2Json;
  valueCertaintyConstraintKind?: StringConstraintKindV2Json;
  valueCertaintyShapeLabel?: string;
  valueCertaintyReason?: string;
  reason?: string;
}
export interface ValueDomainDerivationV2Json {
  schemaVersion: string;
  product: string;
  inputFactKind: string;
  inputConstraintKind?: string;
  inputValueCount: number;
  reducedKind: string;
  steps: ValueDomainDerivationStepV2Json[];
}
export interface ValueDomainDerivationStepV2Json {
  operation: string;
  inputKind?: string;
  refinementKind?: string;
  resultKind: string;
  resultProvenance?: string;
  reason: string;
}
export interface ValueDomainProvenanceTreeV2Json {
  schemaVersion: string;
  product: string;
  valueKind: string;
  value: unknown;
  valueProvenance?: string;
  root: ValueDomainProvenanceNodeV2Json;
}
export interface ValueDomainProvenanceNodeV2Json {
  operation: string;
  resultKind: string;
  resultProvenance?: string;
  detail?: string;
  reason: string;
  children: ValueDomainProvenanceNodeV2Json[];
}
export interface SourceExpressionResolutionQueryResultV2Json {
  kind: "source-expression-resolution";
  filePath: string;
  queryId: string;
  payload: SourceExpressionResolutionPayloadV2Json;
}
export interface SourceExpressionResolutionPayloadV2Json {
  expressionId: string;
  styleFilePath: string | null;
  selectorNames: string[];
  finiteValues: string[] | null;
  selectorCertainty: string;
  selectorCertaintyShapeKind?: CertaintyShapeKindV2Json;
  selectorConstraintKind?: StringConstraintKindV2Json;
  selectorCertaintyShapeLabel?: string;
  selectorCertaintyReason?: string;
  valueCertainty?: string;
  valueCertaintyShapeKind?: CertaintyShapeKindV2Json;
  valueCertaintyConstraintKind?: StringConstraintKindV2Json;
  valuePrefix?: string;
  valueSuffix?: string;
  valueMinLen?: number;
  valueMaxLen?: number;
  valueCharMust?: string;
  valueCharMay?: string;
  valueMayIncludeOtherChars?: boolean;
  valueCertaintyShapeLabel?: string;
  valueCertaintyReason?: string;
  reason?: string;
}
export interface SelectorUsageQueryResultV2Json {
  kind: "selector-usage";
  filePath: string;
  queryId: string;
  payload: SelectorUsagePayloadV2Json;
}
export interface SelectorUsagePayloadV2Json {
  canonicalName: string;
  totalReferences: number;
  directReferenceCount: number;
  editableDirectReferenceCount: number;
  exactReferenceCount: number;
  inferredOrBetterReferenceCount: number;
  hasExpandedReferences: boolean;
  hasStyleDependencyReferences: boolean;
  hasAnyReferences: boolean;
}
export interface TextRewritePlanJsonV2Json {
  payload: unknown;
}
export interface CheckerReportJsonV1Json {
  version: string;
  findings: unknown[];
  summary: unknown;
}
