/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-v2/main.tsp.
// Do not edit this file by hand.

export type ClassnameTransformModeJson = "asIs" | "camelCase" | "dashes" | "dashesOnly";
export type StringTypeFactKindV2Json = "unknown" | "exact" | "finiteSet" | "constrained" | "top";
export type StringConstraintKindV2Json =
  | "prefix"
  | "suffix"
  | "prefixSuffix"
  | "charInclusion"
  | "composite";

export interface EngineInputV2Json {
  version: "2";
  workspace: EngineWorkspaceV1Json;
  sources: SourceAnalysisInputV2Json[];
  styles: StyleAnalysisInputV2Json[];
  typeFacts: TypeFactEntryV2Json[];
}
export interface EngineWorkspaceV1Json {
  root: string;
  classnameTransform: ClassnameTransformModeJson;
  settingsKey: string;
}
export interface SourceAnalysisInputV2Json {
  filePath: string;
  document: unknown;
  bindingGraph?: unknown;
}
export interface StyleAnalysisInputV2Json {
  filePath: string;
  source?: string;
  document: unknown;
}
export interface TypeFactEntryV2Json {
  filePath: string;
  expressionId: string;
  facts: StringTypeFactsV2Json;
}
export interface StringTypeFactsV2Json {
  kind: StringTypeFactKindV2Json;
  values?: string[];
  constraintKind?: StringConstraintKindV2Json;
  prefix?: string;
  suffix?: string;
  minLen?: number;
  maxLen?: number;
  charMust?: string;
  charMay?: string;
  mayIncludeOtherChars?: boolean;
  provenance?: string;
}
