/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-napi/main.tsp.
// Do not edit this file by hand.

export type EngineNapiCascadeOriginV0Json = "userAgent" | "user" | "author" | "inline";
export type EngineNapiBoundaryErrorKindV0Json =
  | "parse-error"
  | "serialize-error"
  | "unsupported-mode";

export interface EngineNapiBoundarySurfaceV0Json {
  readonly context: EngineNapiTransformExecutionContextV0Json;
  readonly targetOptions: EngineNapiTargetTransformOptionsV0Json;
  readonly input: EngineNapiEngineInputV2Json;
  readonly sources: readonly EngineNapiStyleSourceInputV0Json[];
  readonly packageManifests: readonly EngineNapiStylePackageManifestV0Json[];
  readonly sourceDocuments: readonly EngineNapiSourceDocumentInputV0Json[];
  readonly candidates: readonly EngineNapiSourceMissingSelectorDiagnosticCandidateV0Json[];
  readonly importedStyleBindings: readonly EngineNapiSourceImportedStyleBindingInputV0Json[];
  readonly classnamesBindBindings: readonly string[];
  readonly buildSummary: EngineNapiConsumerBuildSummaryV0Json;
  readonly boundaryError: EngineNapiBoundaryErrorV0Json;
}
export interface EngineNapiTransformExecutionContextV0Json {
  readonly dropDarkModeMediaQueries?: boolean;
  readonly supportsTargetCapability?: unknown;
  readonly vendorPrefixPolicy?: EngineNapiVendorPrefixPolicyV0Json;
  readonly reachableClassNames?: readonly string[];
  readonly reachableKeyframeNames?: readonly string[];
  readonly reachableValueNames?: readonly string[];
  readonly reachableCustomPropertyNames?: readonly string[];
  readonly scssModuleEvaluation?: unknown;
  readonly lessModuleEvaluation?: unknown;
  readonly importInlines?: readonly EngineNapiTransformImportInlineV0Json[];
  readonly classNameRewrites?: readonly EngineNapiClassNameRewriteV0Json[];
  readonly cssModuleComposesResolutions?: readonly EngineNapiCssModuleComposesResolutionV0Json[];
  readonly cssModuleValueResolutions?: readonly EngineNapiCssModuleValueResolutionV0Json[];
  readonly designTokenRoutes?: readonly EngineNapiDesignTokenRouteV0Json[];
  readonly cascadeEnvironment?: EngineNapiCascadeEnvironmentV0Json;
}
export interface EngineNapiVendorPrefixPolicyV0Json {
  readonly webkit: boolean;
  readonly moz: boolean;
  readonly ms: boolean;
}
export interface EngineNapiTransformImportInlineV0Json {
  readonly importSource: string;
  readonly replacementCss: string;
}
export interface EngineNapiClassNameRewriteV0Json {
  readonly originalName: string;
  readonly rewrittenName: string;
}
export interface EngineNapiCssModuleComposesResolutionV0Json {
  readonly localClassName: string;
  readonly exportedClassNames: readonly string[];
}
export interface EngineNapiCssModuleValueResolutionV0Json {
  readonly localName: string;
  readonly resolvedValue: string;
}
export interface EngineNapiDesignTokenRouteV0Json {
  readonly tokenName: string;
  readonly routedValue: string;
}
export interface EngineNapiCascadeEnvironmentV0Json {
  readonly stylesheetSourceOrderBase?: number;
  readonly declarations: readonly EngineNapiCascadeEnvironmentDeclarationV0Json[];
}
export interface EngineNapiCascadeEnvironmentDeclarationV0Json {
  readonly declarationId: string;
  readonly selector: string;
  readonly property: string;
  readonly value: string;
  readonly origin: EngineNapiCascadeOriginV0Json;
  readonly important: boolean;
  readonly layerRank?: number;
  readonly scopeProximity?: number;
  readonly sourceOrder: number;
}
export interface EngineNapiTargetTransformOptionsV0Json {
  readonly allowLogicalToPhysical?: boolean;
  readonly allowScopeFlatten?: boolean;
  readonly allowLayerFlatten?: boolean;
  readonly enableSupportsStaticEval?: boolean;
  readonly enableMediaStaticEval?: boolean;
  readonly enableContainerStaticEval?: boolean;
  readonly dropDarkModeMediaQueries?: boolean;
}
export interface EngineNapiEngineInputV2Json {
  readonly version: string;
  readonly workspace: unknown;
  readonly sources: readonly unknown[];
  readonly styles: readonly unknown[];
  readonly typeFacts: readonly unknown[];
}
export interface EngineNapiStyleSourceInputV0Json {
  readonly stylePath: string;
  readonly styleSource: string;
}
export interface EngineNapiStylePackageManifestV0Json {
  readonly packageJsonPath: string;
  readonly packageJsonSource: string;
}
export interface EngineNapiSourceDocumentInputV0Json {
  readonly sourcePath: string;
  readonly sourceSource: string;
  readonly hasUnresolvedStyleImport?: boolean;
}
export interface EngineNapiSourceMissingSelectorDiagnosticCandidateV0Json {
  readonly targetStyleUri: string;
  readonly targetStyleSource: string;
  readonly selectorName: string;
  readonly sourceReferenceRange: EngineNapiRangeV0Json;
}
export interface EngineNapiRangeV0Json {
  readonly start: EngineNapiPositionV0Json;
  readonly end: EngineNapiPositionV0Json;
}
export interface EngineNapiPositionV0Json {
  readonly line: number;
  readonly character: number;
}
export interface EngineNapiSourceImportedStyleBindingInputV0Json {
  readonly binding: string;
  readonly styleUri: string;
}
export interface EngineNapiConsumerBuildSummaryV0Json {
  readonly schemaVersion: string;
  readonly product: string;
  readonly stylePath: string;
  readonly dialect: string;
  readonly requestedPassIds: readonly string[];
  readonly targetQuery?: unknown;
  readonly unknownPassIds: readonly string[];
  readonly execution: unknown;
  readonly semanticRemovalCount: number;
  readonly bundle?: unknown;
  readonly sourceMapV3?: unknown;
  readonly openWorldSnapshot?: unknown;
  readonly readySurfaces: readonly string[];
}
export interface EngineNapiBoundaryErrorV0Json {
  readonly kind: EngineNapiBoundaryErrorKindV0Json;
  readonly message: string;
  readonly functionName?: string;
}
