/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-v2/main.tsp.
// Do not edit this file by hand.

export type ClassnameTransformModeJson =
  | "asIs"
  | "camelCase"
  | "camelCaseOnly"
  | "dashes"
  | "dashesOnly";
export type EngineTextPositionOffsetV2Json = number;
export type EngineStyleImportBindingV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly localName: string;
  readonly bindingDeclId: string;
  readonly resolved: EngineStyleImportV2Json;
};
export type EngineUtilityBindingV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly localName: string;
  readonly bindingDeclId: string;
  readonly stylesLocalName?: string;
  readonly scssModulePath?: string;
  readonly classNamesImportName?: string;
};
export type EngineDomainClassReferenceV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly pluginId: string;
  readonly domain: string;
  readonly origin: string;
  readonly matchKind: string;
  readonly className?: string;
  readonly rawTemplate?: string;
  readonly staticPrefix?: string;
};
export type EngineKeyframesDeclV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly name: string;
  readonly ruleRange: EngineRangeV2Json;
};
export type EngineAnimationNameRefV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly name: string;
  readonly property: string;
};
export type EngineValueDeclV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly name: string;
  readonly value: string;
  readonly ruleRange: EngineRangeV2Json;
};
export type EngineValueImportV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly name: string;
  readonly importedName: string;
  readonly importedNameRange?: EngineRangeV2Json;
  readonly from: string;
  readonly ruleRange: EngineRangeV2Json;
};
export type EngineValueRefV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly name: string;
  readonly source: string;
};
export type EngineCustomPropertyDeclV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly name: string;
  readonly value: string;
  readonly ruleRange: EngineRangeV2Json;
  readonly context: EngineCustomPropertyContextV2Json;
};
export type EngineCustomPropertyRefV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly name: string;
  readonly context: EngineCustomPropertyContextV2Json;
};
export type EngineSassSymbolV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly selectorName: string;
  readonly syntax?: string;
  readonly symbolKind: string;
  readonly name: string;
  readonly role: string;
  readonly resolution: string;
  readonly ruleRange: EngineRangeV2Json;
};
export type EngineSassSymbolDeclV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly syntax?: string;
  readonly symbolKind: string;
  readonly name: string;
  readonly ruleRange: EngineRangeV2Json;
};
export type EngineSassModuleUseV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly source: string;
  readonly namespaceKind: string;
  readonly namespace: string | null;
  readonly ruleRange: EngineRangeV2Json;
};
export type EngineSassModuleForwardV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly source: string;
  readonly prefix: string;
  readonly visibilityKind: string;
  readonly visibilityMembers: readonly EngineSassForwardMemberV2Json[];
  readonly ruleRange: EngineRangeV2Json;
};
export type EngineSassModuleMemberRefV2Json = EngineNodeV2Json & {
  readonly kind: string;
  readonly selectorName: string;
  readonly namespace: string;
  readonly symbolKind: string;
  readonly name: string;
  readonly role: string;
  readonly ruleRange: EngineRangeV2Json;
};
export type StringTypeFactKindV2Json = "unknown" | "exact" | "finiteSet" | "constrained" | "top";
export type StringConstraintKindV2Json =
  | "prefix"
  | "suffix"
  | "prefixSuffix"
  | "charInclusion"
  | "composite";
export type Utf16CodeUnitLengthV2Json = number;
export type TypeFactControlFlowBlockKindV2Json =
  | "entry"
  | "assignment"
  | "branch"
  | "join"
  | "loopHeader"
  | "loopBody"
  | "loopExit"
  | "break"
  | "terminate"
  | "logicalOperand"
  | "logicalRhs"
  | "logicalJoin"
  | "exit";
export type TypeFactControlFlowTransferKindV2Json =
  | "entry"
  | "assignFacts"
  | "branch"
  | "concatFacts"
  | "join"
  | "loop"
  | "break"
  | "terminate"
  | "exit";
export type TypeFactControlFlowExpressionKindV2Json =
  | "logicalAnd"
  | "logicalOr"
  | "nullishCoalesce";
export type ClassBoundaryEffectV2Json =
  | "concatInsideToken"
  | "concatAtTokenBoundary"
  | "unknownBoundary";

export interface EngineInputV2Json {
  readonly version: "2";
  readonly workspace: EngineWorkspaceV1Json;
  readonly sources: readonly SourceAnalysisInputV2Json[];
  readonly styles: readonly StyleAnalysisInputV2Json[];
  readonly typeFacts: readonly TypeFactEntryV2Json[];
}
export interface EngineWorkspaceV1Json {
  readonly root: string;
  readonly classnameTransform: ClassnameTransformModeJson;
  readonly settingsKey: string;
}
export interface SourceAnalysisInputV2Json {
  readonly filePath: string;
  readonly document: EngineSourceDocumentV2Json;
  readonly bindingGraph?: EngineBindingGraphV2Json;
}
export interface EngineSourceDocumentV2Json {
  readonly kind?: string;
  readonly filePath?: string;
  readonly language?: string;
  readonly classExpressions: readonly EngineClassExpressionV2Json[];
  readonly styleImports?: readonly EngineStyleImportBindingV2Json[];
  readonly utilityBindings?: readonly EngineUtilityBindingV2Json[];
  readonly domainClassReferences?: readonly EngineDomainClassReferenceV2Json[];
}
export interface EngineClassExpressionV2Json {
  readonly id: string;
  readonly kind: string;
  readonly scssModulePath: string;
  readonly range: EngineRangeV2Json;
  readonly origin?: string;
  readonly className?: string;
  readonly rootBindingDeclId?: string;
  readonly accessPath?: readonly string[];
  readonly rawTemplate?: string;
  readonly staticPrefix?: string;
  readonly rawReference?: string;
  readonly rootName?: string;
  readonly pathSegments?: readonly string[];
  readonly bindingDeclId?: string;
}
export interface EngineRangeV2Json {
  readonly start: EnginePositionV2Json;
  readonly end: EnginePositionV2Json;
}
export interface EnginePositionV2Json {
  readonly line: EngineTextPositionOffsetV2Json;
  readonly character: EngineTextPositionOffsetV2Json;
}
export interface EngineNodeV2Json {
  readonly id?: string;
  readonly range?: EngineRangeV2Json;
}
export interface EngineStyleImportV2Json {
  readonly kind: string;
  readonly absolutePath: string;
  readonly specifier?: string;
  readonly range?: EngineRangeV2Json;
}
export interface EngineBindingGraphV2Json {
  readonly declarations: readonly EngineBindingDeclarationV2Json[];
  readonly resolutions: readonly EngineBindingResolutionV2Json[];
}
export interface EngineBindingDeclarationV2Json {
  readonly id: string;
  readonly name: string;
  readonly kind: string;
}
export interface EngineBindingResolutionV2Json {
  readonly expressionId: string;
  readonly declarationId: string | null;
}
export interface StyleAnalysisInputV2Json {
  readonly filePath: string;
  readonly source?: string;
  readonly document: EngineStyleDocumentV2Json;
}
export interface EngineStyleDocumentV2Json {
  readonly kind?: string;
  readonly filePath?: string;
  readonly selectors: readonly EngineStyleSelectorV2Json[];
  readonly keyframes?: readonly EngineKeyframesDeclV2Json[];
  readonly animationNameRefs?: readonly EngineAnimationNameRefV2Json[];
  readonly valueDecls?: readonly EngineValueDeclV2Json[];
  readonly valueImports?: readonly EngineValueImportV2Json[];
  readonly valueRefs?: readonly EngineValueRefV2Json[];
  readonly customPropertyDecls?: readonly EngineCustomPropertyDeclV2Json[];
  readonly customPropertyRefs?: readonly EngineCustomPropertyRefV2Json[];
  readonly sassSymbols?: readonly EngineSassSymbolV2Json[];
  readonly sassSymbolDecls?: readonly EngineSassSymbolDeclV2Json[];
  readonly sassModuleUses?: readonly EngineSassModuleUseV2Json[];
  readonly sassModuleForwards?: readonly EngineSassModuleForwardV2Json[];
  readonly sassModuleMemberRefs?: readonly EngineSassModuleMemberRefV2Json[];
}
export interface EngineStyleSelectorV2Json {
  readonly name: string;
  readonly viewKind: string;
  readonly range: EngineRangeV2Json;
  readonly id?: string;
  readonly kind?: string;
  readonly canonicalName?: string;
  readonly nestedSafety?: string;
  readonly composes?: readonly EngineComposesRefV2Json[];
  readonly bemSuffix?: EngineBemSuffixV2Json;
  readonly fullSelector?: string;
  readonly declarations?: string;
  readonly ruleRange?: EngineRangeV2Json;
  readonly originalName?: string;
  readonly context?: EngineSelectorContextV2Json;
}
export interface EngineComposesRefV2Json {
  readonly classNames: readonly string[];
  readonly range?: EngineRangeV2Json;
  readonly classTokens?: readonly EngineComposesClassTokenV2Json[];
  readonly from?: string;
  readonly fromGlobal?: boolean;
}
export interface EngineComposesClassTokenV2Json {
  readonly className: string;
  readonly range: EngineRangeV2Json;
}
export interface EngineBemSuffixV2Json {
  readonly rawTokenRange: EngineRangeV2Json;
  readonly rawToken?: string;
  readonly parentResolvedName?: string;
}
export interface EngineSelectorContextV2Json {
  readonly wrapperAtRules: readonly EngineAtRuleContextV2Json[];
}
export interface EngineAtRuleContextV2Json {
  readonly name: string;
  readonly params: string;
  readonly range: EngineRangeV2Json;
}
export interface EngineCustomPropertyContextV2Json {
  readonly containerKind: string;
  readonly selectorText: string | null;
  readonly atRuleName: string | null;
  readonly atRuleParams: string | null;
  readonly wrapperAtRules: readonly EngineAtRuleContextV2Json[];
}
export interface EngineSassForwardMemberV2Json {
  readonly name: string;
  readonly symbolKind: string | null;
}
export interface TypeFactEntryV2Json {
  readonly filePath: string;
  readonly expressionId: string;
  readonly facts: StringTypeFactsV2Json;
  readonly controlFlowGraph?: TypeFactControlFlowGraphV2Json;
}
export interface StringTypeFactsV2Json {
  readonly kind: StringTypeFactKindV2Json;
  readonly values?: readonly string[];
  readonly constraintKind?: StringConstraintKindV2Json;
  readonly prefix?: string;
  readonly suffix?: string;
  readonly minLen?: Utf16CodeUnitLengthV2Json;
  readonly maxLen?: Utf16CodeUnitLengthV2Json;
  readonly charMust?: string;
  readonly charMay?: string;
  readonly mayIncludeOtherChars?: boolean;
  readonly provenance?: string;
}
export interface TypeFactControlFlowGraphV2Json {
  readonly entryBlockId: string;
  readonly blocks: readonly TypeFactControlFlowBlockV2Json[];
}
export interface TypeFactControlFlowBlockV2Json {
  readonly id: string;
  readonly kind: TypeFactControlFlowBlockKindV2Json;
  readonly transferKind: TypeFactControlFlowTransferKindV2Json;
  readonly successorBlockIds: readonly string[];
  readonly symbolOrdinal?: number;
  readonly variableName?: string;
  readonly expressionKind?: TypeFactControlFlowExpressionKindV2Json;
  readonly boundaryEffect: ClassBoundaryEffectV2Json;
  readonly facts?: StringTypeFactsV2Json;
}
