/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-sdk-workflow/main.tsp.
// Do not edit this file by hand.

import type {
  EngineNapiEngineInputV2Json,
  EngineNapiStylePackageManifestV0Json,
  EngineNapiStyleSourceInputV0Json,
  EngineNapiTransformExecutionContextV0Json,
} from "./engine-napi-boundary-idl.generated";

export type OmenaErrorClassV0Json =
  | "input"
  | "workspace"
  | "resolution"
  | "analysis"
  | "transform"
  | "unsupported"
  | "internal"
  | "unknown";
export type OmenaErrorSeverityV0Json = "error" | "warning" | "information";
export type OmenaErrorRecoverabilityV0Json = "retry" | "user-action" | "not-recoverable";
export type OmenaSdkResponsePartitionV0Json = "public" | "debug";
export type EngineNapiCascadeOriginV0Json = "userAgent" | "user" | "author" | "inline";
export type OmenaWorkspaceSessionOperationV0Json =
  | "diagnostics"
  | "format"
  | "lint"
  | "check"
  | "explain"
  | "replaceStyleSources"
  | "cancel"
  | "shutdown";
export type OmenaClosedWorldOutcomeV0Json =
  | OmenaClosedWorldClosedOutcomeV0Json
  | OmenaClosedWorldOpenOutcomeV0Json;
export type OmenaClosedWorldInterfaceHashAvailabilityV0Json =
  | OmenaClosedWorldInterfaceHashKnownV0Json
  | OmenaClosedWorldInterfaceHashAbsentV0Json;
export type OmenaClosedWorldBlockerV0Json =
  | OmenaClosedWorldEmptyEntrypointsBlockerV0Json
  | OmenaClosedWorldMissingEntrypointBlockerV0Json
  | OmenaClosedWorldAmbiguousModulePathBlockerV0Json
  | OmenaClosedWorldMissingDependencyBlockerV0Json
  | OmenaClosedWorldMissingModuleInstanceBlockerV0Json
  | OmenaClosedWorldMissingModuleDependencyBlockerV0Json
  | OmenaClosedWorldPassUnavailableBlockerV0Json;
export type OmenaGuaranteeKindV0Json =
  | "floor"
  | "sampledFixtureWitness"
  | "schedulerPriorityFixtureWitness"
  | "metricInputFixtureWitness"
  | "incrementalLayerEvidenceOnly"
  | "alphaRenamingStableHashFixtureWitness"
  | "notClaimedExactTraversal";

export interface OmenaSdkWorkflowSurfaceV0Json {
  readonly errorEnvelope: OmenaSdkErrorEnvelopeV0Json;
  readonly cliResponseEnvelope: OmenaCliResponseEnvelopeV0Json;
  readonly snapshotRequest: OmenaSdkSnapshotRequestV0Json;
  readonly snapshotResponse: OmenaSdkSnapshotResponseV0Json;
  readonly queryRequest: OmenaSdkQueryRequestV0Json;
  readonly queryResponse: OmenaSdkQueryResponseV0Json;
  readonly diagnosticsRequest: OmenaSdkDiagnosticsRequestV0Json;
  readonly diagnosticsResponse: OmenaSdkDiagnosticsResponseV0Json;
  readonly diagnosticsDebugReport: OmenaSdkDiagnosticsDebugReportV0Json;
  readonly buildRequest: OmenaSdkBuildRequestV0Json;
  readonly buildResponse: OmenaSdkBuildResponseV0Json;
  readonly explainRequest: OmenaSdkExplainRequestV0Json;
  readonly explainResponse: OmenaSdkExplainResponseV0Json;
  readonly workspaceSessionHandshakeRequest: OmenaWorkspaceSessionHandshakeRequestV0Json;
  readonly workspaceSessionHandshakeResponse: OmenaWorkspaceSessionHandshakeResponseV0Json;
  readonly workspaceSessionRequest: OmenaWorkspaceSessionRequestV0Json;
  readonly workspaceSessionResponse: OmenaWorkspaceSessionResponseV0Json;
  readonly bundlerHostCapabilities: OmenaBundlerHostCapabilitiesV0Json;
  readonly bundlerHostResolveModuleRequest: OmenaBundlerHostResolveModuleRequestV0Json;
  readonly bundlerHostResolveModuleResponse: OmenaBundlerHostResolveModuleResponseV0Json;
  readonly bundlerHostBundleAdmission: OmenaBundlerHostBundleAdmissionV0Json;
}
export interface OmenaSdkErrorEnvelopeV0Json {
  readonly error: OmenaErrorV0Json;
}
export interface OmenaErrorV0Json {
  readonly class: OmenaErrorClassV0Json;
  readonly message: string;
  readonly context: OmenaErrorContextV0Json;
}
export interface OmenaErrorContextV0Json {
  readonly code: string;
  readonly severity: OmenaErrorSeverityV0Json;
  readonly recoverability: OmenaErrorRecoverabilityV0Json;
  readonly evidence?: readonly OmenaErrorEvidenceReferenceV0Json[];
}
export interface OmenaErrorEvidenceReferenceV0Json {
  readonly queryIdentity: string;
  readonly inputIdentity: string;
}
export interface OmenaCliResponseEnvelopeV0Json {
  readonly schemaVersion: "0";
  readonly product: string;
  readonly configContentDigest?: string;
  readonly payload: unknown;
}
export interface OmenaSdkSnapshotRequestV0Json {
  readonly workspaceRoot: string;
}
export interface OmenaSdkSnapshotResponseV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly workspaceRoot: string;
}
export interface OmenaWorkspaceSnapshotIdV0Json {
  readonly value: number;
}
export interface OmenaSdkQueryRequestV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly queryKind: string;
  readonly input?: EngineNapiEngineInputV2Json;
}
export interface OmenaSdkQueryResponseV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly payload: unknown;
}
export interface OmenaSdkDiagnosticsRequestV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly stylePath: string;
  readonly styleSource: string;
}
export interface OmenaSdkDiagnosticsResponseV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly summary: OmenaSdkDiagnosticsSummaryV0Json;
}
export interface OmenaSdkDiagnosticsSummaryV0Json {
  readonly schemaVersion: string;
  readonly product: string;
  readonly stylePath: string;
  readonly dialect: string;
  readonly tokenCount: number;
  readonly parserErrorCount: number;
  readonly classSelectorCount: number;
  readonly customPropertyCount: number;
  readonly keyframeCount: number;
  readonly readySurfaces: readonly string[];
}
export interface OmenaSdkDiagnosticsDebugReportV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly publicResponse: OmenaSdkDiagnosticsResponseV0Json;
  readonly analysis: unknown;
}
export interface OmenaSdkBuildRequestV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly stylePath: string;
  readonly styleSource: string;
  readonly passIds: readonly string[];
  readonly context?: EngineNapiTransformExecutionContextV0Json;
}
export interface OmenaSdkBuildResponseV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly summary: unknown;
}
export interface OmenaSdkExplainRequestV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly stylePath: string;
  readonly position: OmenaSdkExplainPositionV0Json;
}
export interface OmenaSdkExplainPositionV0Json {
  readonly line: number;
  readonly character: number;
}
export interface OmenaSdkExplainResponseV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly report: unknown;
}
export interface OmenaWorkspaceSessionHandshakeRequestV0Json {
  readonly protocolVersion: "0";
  readonly workspaceRoot: string;
  readonly configContentDigest?: string;
  readonly styleSources: readonly EngineNapiStyleSourceInputV0Json[];
  readonly limits: OmenaWorkspaceSessionLimitsV0Json;
}
export interface OmenaWorkspaceSessionLimitsV0Json {
  readonly deadlineMs: number;
  readonly maxResponseBytes: number;
}
export interface OmenaWorkspaceSessionHandshakeResponseV0Json {
  readonly protocolVersion: "0";
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly workspaceRoot: string;
  readonly configContentDigest?: string;
  readonly capabilities: readonly string[];
}
export interface OmenaWorkspaceSessionRequestV0Json {
  readonly requestId: string;
  readonly protocolVersion: "0";
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly operation: OmenaWorkspaceSessionOperationV0Json;
  readonly limits: OmenaWorkspaceSessionLimitsV0Json;
  readonly payload?: unknown;
}
export interface OmenaWorkspaceSessionResponseV0Json {
  readonly requestId: string;
  readonly protocolVersion: "0";
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly ok: boolean;
  readonly payload?: unknown;
  readonly error?: OmenaErrorV0Json;
}
export interface OmenaBundlerHostCapabilitiesV0Json {
  readonly protocolVersion: "0";
  readonly capabilities: readonly string[];
}
export interface OmenaBundlerHostResolveModuleRequestV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly stylePath: string;
  readonly styleSources: readonly EngineNapiStyleSourceInputV0Json[];
  readonly packageManifests: readonly EngineNapiStylePackageManifestV0Json[];
}
export interface OmenaBundlerHostResolveModuleResponseV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly protocolVersion: "0";
  readonly moduleId: string;
  readonly classMap: RecordStringJson;
  readonly namedExports: RecordStringJson;
  readonly typescriptDeclaration: string;
  readonly composesEdges: readonly OmenaBundlerHostComposesEdgeV0Json[];
  readonly diagnostics: readonly OmenaBundlerHostDiagnosticV0Json[];
  readonly ready: boolean;
}
export type RecordStringJson = Readonly<Record<string, string>>;
export interface OmenaBundlerHostComposesEdgeV0Json {
  readonly exportedName: string;
  readonly moduleId: string;
  readonly className: string;
}
export interface OmenaBundlerHostDiagnosticV0Json {
  readonly code: string;
  readonly message: string;
}
export interface OmenaBundlerHostBundleAdmissionV0Json {
  readonly closedWorldOutcome: OmenaClosedWorldOutcomeV0Json;
  readonly closedWorldDecisionParity: OmenaClosedWorldDecisionParityV0Json;
  readonly evidence: OmenaBundleEvidenceManifestV0Json;
}
export interface OmenaClosedWorldClosedOutcomeV0Json {
  readonly status: "closed";
  readonly bundle: OmenaClosedWorldBundleV0Json;
}
export interface OmenaClosedWorldBundleV0Json {
  readonly entrypoints: readonly OmenaModuleInstanceKeyV0Json[];
  readonly linkedModules: readonly OmenaModuleInstanceKeyV0Json[];
  readonly reachability: OmenaClosedWorldReachabilityIndexV0Json;
  readonly closureHash: string;
  readonly interfaceHashes?: OmenaClosedWorldInterfaceHashSetV0Json;
  readonly sourcePrecision?: OmenaClosedWorldSourcePrecisionSummaryV0Json;
}
export interface OmenaModuleInstanceKeyV0Json {
  readonly module: string;
  readonly configuration: string;
}
export interface OmenaClosedWorldReachabilityIndexV0Json {
  readonly moduleInstances: readonly OmenaModuleInstanceKeyV0Json[];
  readonly classNames: readonly string[];
  readonly keyframeNames: readonly string[];
  readonly valueNames: readonly string[];
  readonly customPropertyNames: readonly string[];
}
export interface OmenaClosedWorldInterfaceHashSetV0Json {
  readonly entries: readonly OmenaClosedWorldInterfaceHashEntryV0Json[];
}
export interface OmenaClosedWorldInterfaceHashEntryV0Json {
  readonly moduleInstance: OmenaModuleInstanceKeyV0Json;
  readonly availability: OmenaClosedWorldInterfaceHashAvailabilityV0Json;
}
export interface OmenaClosedWorldInterfaceHashKnownV0Json {
  readonly status: "known";
  readonly interfaceHash: string;
}
export interface OmenaClosedWorldInterfaceHashAbsentV0Json {
  readonly status: "absent";
}
export interface OmenaClosedWorldSourcePrecisionSummaryV0Json {
  readonly exactSourceCount: number;
  readonly conservativeSourceCount: number;
  readonly heuristicSourceCount: number;
  readonly unknownSourceCount: number;
}
export interface OmenaClosedWorldOpenOutcomeV0Json {
  readonly status: "open";
  readonly blockers: readonly OmenaClosedWorldBlockerV0Json[];
}
export interface OmenaClosedWorldEmptyEntrypointsBlockerV0Json {
  readonly kind: "emptyEntrypoints";
}
export interface OmenaClosedWorldMissingEntrypointBlockerV0Json {
  readonly kind: "missingEntrypoint";
  readonly sourcePath: string;
}
export interface OmenaClosedWorldAmbiguousModulePathBlockerV0Json {
  readonly kind: "ambiguousModulePath";
  readonly sourcePath: string;
}
export interface OmenaClosedWorldMissingDependencyBlockerV0Json {
  readonly kind: "missingDependency";
  readonly sourcePath: string;
  readonly importSource: string;
}
export interface OmenaClosedWorldMissingModuleInstanceBlockerV0Json {
  readonly kind: "missingModuleInstance";
  readonly module: OmenaModuleInstanceKeyV0Json;
}
export interface OmenaClosedWorldMissingModuleDependencyBlockerV0Json {
  readonly kind: "missingModuleDependency";
  readonly module: OmenaModuleInstanceKeyV0Json;
  readonly dependency: OmenaModuleInstanceKeyV0Json;
}
export interface OmenaClosedWorldPassUnavailableBlockerV0Json {
  readonly kind: "closedWorldPassUnavailable";
  readonly requestedPassIds: readonly string[];
}
export interface OmenaClosedWorldDecisionParityV0Json {
  readonly legacyOpenDecision: boolean;
  readonly typedOutcomeOpen: boolean;
  readonly equivalent: boolean;
}
export interface OmenaBundleEvidenceManifestV0Json {
  readonly schemaVersion: "0";
  readonly product: "omena-query.bundle-evidence";
  readonly stylePath: string;
  readonly outcomeStatus: "closed" | "open";
  readonly reachability: OmenaBundleReachabilityEvidenceV0Json | null;
  readonly gates: readonly OmenaBundleEvidenceGateV0Json[];
  readonly blockers: readonly OmenaClosedWorldBlockerV0Json[];
  readonly interfaceHashes: readonly OmenaClosedWorldInterfaceHashEntryV0Json[];
  readonly sourcePrecision: OmenaClosedWorldSourcePrecisionSummaryV0Json | null;
}
export interface OmenaBundleReachabilityEvidenceV0Json {
  readonly guarantee: OmenaGuaranteeKindV0Json;
  readonly interpretation: string;
  readonly moduleInstances: readonly OmenaModuleInstanceKeyV0Json[];
  readonly closureHash: string;
}
export interface OmenaBundleEvidenceGateV0Json {
  readonly name: string;
  readonly passed: boolean;
}
