/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-sdk-workflow/main.tsp.
// Do not edit this file by hand.

import type {
  EngineNapiEngineInputV2Json,
  EngineNapiTransformExecutionContextV0Json,
} from "./engine-napi-boundary-idl.generated";

export type OmenaErrorClassV0Json =
  | "input"
  | "workspace"
  | "resolution"
  | "analysis"
  | "transform"
  | "unsupported"
  | "internal"
  | "unknown";
export type OmenaErrorSeverityV0Json = "error" | "warning" | "information";
export type OmenaErrorRecoverabilityV0Json = "retry" | "user-action" | "not-recoverable";
export type OmenaSdkResponsePartitionV0Json = "public" | "debug";

export interface OmenaSdkWorkflowSurfaceV0Json {
  readonly errorEnvelope: OmenaSdkErrorEnvelopeV0Json;
  readonly cliResponseEnvelope: OmenaCliResponseEnvelopeV0Json;
  readonly snapshotRequest: OmenaSdkSnapshotRequestV0Json;
  readonly snapshotResponse: OmenaSdkSnapshotResponseV0Json;
  readonly queryRequest: OmenaSdkQueryRequestV0Json;
  readonly queryResponse: OmenaSdkQueryResponseV0Json;
  readonly diagnosticsRequest: OmenaSdkDiagnosticsRequestV0Json;
  readonly diagnosticsResponse: OmenaSdkDiagnosticsResponseV0Json;
  readonly diagnosticsDebugReport: OmenaSdkDiagnosticsDebugReportV0Json;
  readonly buildRequest: OmenaSdkBuildRequestV0Json;
  readonly buildResponse: OmenaSdkBuildResponseV0Json;
  readonly explainRequest: OmenaSdkExplainRequestV0Json;
  readonly explainResponse: OmenaSdkExplainResponseV0Json;
}
export interface OmenaSdkErrorEnvelopeV0Json {
  readonly error: OmenaErrorV0Json;
}
export interface OmenaErrorV0Json {
  readonly class: OmenaErrorClassV0Json;
  readonly message: string;
  readonly context: OmenaErrorContextV0Json;
}
export interface OmenaErrorContextV0Json {
  readonly code: string;
  readonly severity: OmenaErrorSeverityV0Json;
  readonly recoverability: OmenaErrorRecoverabilityV0Json;
}
export interface OmenaCliResponseEnvelopeV0Json {
  readonly schemaVersion: "0";
  readonly product: string;
  readonly configContentDigest?: string;
  readonly payload: unknown;
}
export interface OmenaSdkSnapshotRequestV0Json {
  readonly workspaceRoot: string;
}
export interface OmenaSdkSnapshotResponseV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly workspaceRoot: string;
}
export interface OmenaWorkspaceSnapshotIdV0Json {
  readonly value: number;
}
export interface OmenaSdkQueryRequestV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly queryKind: string;
  readonly input?: EngineNapiEngineInputV2Json;
}
export interface OmenaSdkQueryResponseV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly payload: unknown;
}
export interface OmenaSdkDiagnosticsRequestV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly stylePath: string;
  readonly styleSource: string;
}
export interface OmenaSdkDiagnosticsResponseV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly summary: OmenaSdkDiagnosticsSummaryV0Json;
}
export interface OmenaSdkDiagnosticsSummaryV0Json {
  readonly schemaVersion: string;
  readonly product: string;
  readonly stylePath: string;
  readonly dialect: string;
  readonly tokenCount: number;
  readonly parserErrorCount: number;
  readonly classSelectorCount: number;
  readonly customPropertyCount: number;
  readonly keyframeCount: number;
  readonly readySurfaces: readonly string[];
}
export interface OmenaSdkDiagnosticsDebugReportV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly publicResponse: OmenaSdkDiagnosticsResponseV0Json;
  readonly analysis: unknown;
}
export interface OmenaSdkBuildRequestV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly stylePath: string;
  readonly styleSource: string;
  readonly passIds: readonly string[];
  readonly context?: EngineNapiTransformExecutionContextV0Json;
}
export interface OmenaSdkBuildResponseV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly summary: unknown;
}
export interface OmenaSdkExplainRequestV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly stylePath: string;
  readonly position: OmenaSdkExplainPositionV0Json;
}
export interface OmenaSdkExplainPositionV0Json {
  readonly line: number;
  readonly character: number;
}
export interface OmenaSdkExplainResponseV0Json {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0Json;
  readonly partition: OmenaSdkResponsePartitionV0Json;
  readonly report: unknown;
}
