/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-v2/main.tsp.
// Do not edit this file by hand.

export type ClassnameTransformModeJson =
  | "asIs"
  | "camelCase"
  | "camelCaseOnly"
  | "dashes"
  | "dashesOnly";
export type StringTypeFactKindV2Json = "unknown" | "exact" | "finiteSet" | "constrained" | "top";
export type StringConstraintKindV2Json =
  | "prefix"
  | "suffix"
  | "prefixSuffix"
  | "charInclusion"
  | "composite";
export type TypeFactControlFlowBlockKindV2Json =
  | "entry"
  | "assignment"
  | "branch"
  | "join"
  | "loopHeader"
  | "loopBody"
  | "loopExit"
  | "break"
  | "terminate"
  | "logicalOperand"
  | "logicalRhs"
  | "logicalJoin"
  | "exit";
export type TypeFactControlFlowTransferKindV2Json =
  | "entry"
  | "assignFacts"
  | "branch"
  | "concatFacts"
  | "join"
  | "loop"
  | "break"
  | "terminate"
  | "exit";
export type TypeFactControlFlowExpressionKindV2Json =
  | "logicalAnd"
  | "logicalOr"
  | "nullishCoalesce";

export interface EngineInputV2Json {
  readonly version: "2";
  readonly workspace: EngineWorkspaceV1Json;
  readonly sources: readonly SourceAnalysisInputV2Json[];
  readonly styles: readonly StyleAnalysisInputV2Json[];
  readonly typeFacts: readonly TypeFactEntryV2Json[];
}
export interface EngineWorkspaceV1Json {
  readonly root: string;
  readonly classnameTransform: ClassnameTransformModeJson;
  readonly settingsKey: string;
}
export interface SourceAnalysisInputV2Json {
  readonly filePath: string;
  readonly document: unknown;
  readonly bindingGraph?: unknown;
}
export interface StyleAnalysisInputV2Json {
  readonly filePath: string;
  readonly source?: string;
  readonly document: unknown;
}
export interface TypeFactEntryV2Json {
  readonly filePath: string;
  readonly expressionId: string;
  readonly facts: StringTypeFactsV2Json;
  readonly controlFlowGraph?: TypeFactControlFlowGraphV2Json;
}
export interface StringTypeFactsV2Json {
  readonly kind: StringTypeFactKindV2Json;
  readonly values?: readonly string[];
  readonly constraintKind?: StringConstraintKindV2Json;
  readonly prefix?: string;
  readonly suffix?: string;
  readonly minLen?: number;
  readonly maxLen?: number;
  readonly charMust?: string;
  readonly charMay?: string;
  readonly mayIncludeOtherChars?: boolean;
  readonly provenance?: string;
}
export interface TypeFactControlFlowGraphV2Json {
  readonly entryBlockId: string;
  readonly blocks: readonly TypeFactControlFlowBlockV2Json[];
}
export interface TypeFactControlFlowBlockV2Json {
  readonly id: string;
  readonly kind: TypeFactControlFlowBlockKindV2Json;
  readonly transferKind: TypeFactControlFlowTransferKindV2Json;
  readonly successorBlockIds: readonly string[];
  readonly variableName?: string;
  readonly expressionKind?: TypeFactControlFlowExpressionKindV2Json;
  readonly facts?: StringTypeFactsV2Json;
}
