/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/external-corpus-envelope/main.tsp.
// Do not edit this file by hand.

export type ExternalCorpusStageV1Json = "stage1-advisory" | "stage2-blocking";
export type ExternalCorpusDialectV1Json = "css" | "scss" | "sass" | "less";
export type ExternalCorpusExpectationKindV1Json =
  | "static-must-match"
  | "expected-sound-bail"
  | "parser-recovery"
  | "out-of-scope"
  | "finding-census";
export type ExternalCorpusSourceV1Json =
  | ExternalCorpusSourcePinV1Json
  | ExternalCorpusLocalWorkspaceSourceV1Json;

export interface ExternalCorpusEnvelopeV1Json {
  readonly schemaVersion: string;
  readonly product: string;
  readonly stage: ExternalCorpusStageV1Json;
  readonly dialect?: ExternalCorpusDialectV1Json;
  readonly expectationKind?: ExternalCorpusExpectationKindV1Json;
  readonly source: ExternalCorpusSourceV1Json;
  readonly knownFailurePolicy?: ExternalCorpusKnownFailurePolicyRefV1Json;
  readonly generation: ExternalCorpusGenerationProvenanceV1Json;
  readonly provenance?: ExternalCorpusProvenanceV1Json;
  readonly sparsePathFixtureCounts?: readonly ExternalCorpusSparsePathFixtureCountV1Json[];
  readonly chunks: readonly ExternalCorpusChunkV1Json[];
  readonly greenRuns?: readonly ExternalCorpusGreenRunV1Json[];
}
export interface ExternalCorpusSourcePinV1Json {
  readonly kind: "pinned-repository";
  readonly repository: string;
  readonly pin: string;
  readonly sparsePaths: readonly string[];
  readonly helperClasses: readonly string[];
  readonly layoutDependentHelpersExcluded: readonly string[];
}
export interface ExternalCorpusLocalWorkspaceSourceV1Json {
  readonly kind: "local-workspace";
  readonly workspacePath: string;
}
export interface ExternalCorpusKnownFailurePolicyRefV1Json {
  readonly path: string;
  readonly schemaVersion: string;
  readonly stage2Blocking: boolean;
}
export interface ExternalCorpusGenerationProvenanceV1Json {
  readonly tool: string;
  readonly selectionPath: string;
  readonly oraclePinRefs?: readonly string[];
}
export interface ExternalCorpusProvenanceV1Json {
  readonly generationTool: string;
  readonly selectionPath: string;
  readonly oraclePinRefs: readonly string[];
}
export interface ExternalCorpusSparsePathFixtureCountV1Json {
  readonly sparsePath: string;
  readonly fixtureCount: number;
}
export interface ExternalCorpusChunkV1Json {
  readonly chunkId: string;
  readonly path: string;
  readonly stage: ExternalCorpusStageV1Json;
  readonly sha256: string;
  readonly fixtureCount: number;
  readonly sparsePathFixtureCounts?: readonly ExternalCorpusSparsePathFixtureCountV1Json[];
}
export interface ExternalCorpusGreenRunV1Json {
  readonly date: string;
  readonly commit: string;
  readonly fixtureCount: number;
  readonly chunkSha256: string;
  readonly outcomeOlw?: number;
  readonly criticalRegressionCount: number;
  readonly command: string;
}
