/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/parse-tree/main.tsp.
// Do not edit this file by hand.

export interface ParseTreeNodeV0Json {
  readonly kind: string;
  byteSpan: {
    start: number;
    end: number;
  };
  range: {
    start: {
      line: number;
      character: number;
    };
    end: {
      line: number;
      character: number;
    };
  };
  readonly text?: string;
  readonly children: readonly ParseTreeNodeV0Json1[];
  readonly bogus?: boolean;
  readonly error?: string;
}
export interface ParseTreeNodeV0Json1 {
  readonly kind: string;
  byteSpan: {
    start: number;
    end: number;
  };
  range: {
    start: {
      line: number;
      character: number;
    };
    end: {
      line: number;
      character: number;
    };
  };
  readonly text?: string;
  readonly children: readonly ParseTreeNodeV0Json1[];
  readonly bogus?: boolean;
  readonly error?: string;
}
