/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/property-metadata/main.tsp.
// Do not edit this file by hand.

export interface CssPropertyMetadataV1Json {
  readonly schemaVersion: string;
  readonly product: string;
  readonly source: CssPropertyMetadataSourceV1Json;
  readonly customPropertyPolicy: CssCustomPropertyPolicyV1Json;
  readonly properties: readonly CssPropertyMetadataRecordV1Json[];
}
export interface CssPropertyMetadataSourceV1Json {
  readonly package: string;
  readonly version: string;
  readonly sourcePath: string;
  readonly tool: string;
}
export interface CssCustomPropertyPolicyV1Json {
  readonly inherited: boolean;
  readonly initialValue: string;
}
export interface CssPropertyMetadataRecordV1Json {
  readonly propertyId: string;
  readonly canonicalName: string;
  readonly inherited: boolean;
  readonly initialValue: string;
}
