/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-sdk-workflow/main.tsp.
// Do not edit this file by hand.

export type OmenaClosedWorldOutcomeV0 =
  | OmenaClosedWorldClosedOutcomeV0
  | OmenaClosedWorldOpenOutcomeV0;
export type OmenaClosedWorldInterfaceHashAvailabilityV0 =
  | OmenaClosedWorldInterfaceHashKnownV0
  | OmenaClosedWorldInterfaceHashAbsentV0;
export type OmenaClosedWorldBlockerV0 =
  | OmenaClosedWorldEmptyEntrypointsBlockerV0
  | OmenaClosedWorldMissingEntrypointBlockerV0
  | OmenaClosedWorldAmbiguousModulePathBlockerV0
  | OmenaClosedWorldMissingDependencyBlockerV0
  | OmenaClosedWorldMissingModuleInstanceBlockerV0
  | OmenaClosedWorldMissingModuleDependencyBlockerV0
  | OmenaClosedWorldPassUnavailableBlockerV0;
export type OmenaGuaranteeKindV0 =
  | "floor"
  | "sampledFixtureWitness"
  | "schedulerPriorityFixtureWitness"
  | "metricInputFixtureWitness"
  | "incrementalLayerEvidenceOnly"
  | "alphaRenamingStableHashFixtureWitness"
  | "notClaimedExactTraversal";

export interface OmenaBundlerHostPackageContractV0 {
  readonly resolveModuleResponse: OmenaBundlerHostResolveModuleResponseV0;
  readonly bundleAdmission: OmenaBundlerHostBundleAdmissionV0;
}
export interface OmenaBundlerHostResolveModuleResponseV0 {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0;
  readonly protocolVersion: "0";
  readonly moduleId: string;
  readonly classMap: OmenaBundlerHostStringRecordV0;
  readonly namedExports: OmenaBundlerHostStringRecordV0;
  readonly typescriptDeclaration: string;
  readonly composesEdges: readonly OmenaBundlerHostComposesEdgeV0[];
  readonly diagnostics: readonly OmenaBundlerHostDiagnosticV0[];
  readonly ready: boolean;
}
export interface OmenaWorkspaceSnapshotIdV0 {
  readonly value: number;
}
export type OmenaBundlerHostStringRecordV0 = Readonly<Record<string, string>>;
export interface OmenaBundlerHostComposesEdgeV0 {
  readonly exportedName: string;
  readonly moduleId: string;
  readonly className: string;
}
export interface OmenaBundlerHostDiagnosticV0 {
  readonly code: string;
  readonly message: string;
}
export interface OmenaBundlerHostBundleAdmissionV0 {
  readonly closedWorldOutcome: OmenaClosedWorldOutcomeV0;
  readonly closedWorldDecisionParity: OmenaClosedWorldDecisionParityV0;
  readonly evidence: OmenaBundleEvidenceManifestV0;
}
export interface OmenaClosedWorldClosedOutcomeV0 {
  readonly status: "closed";
  readonly bundle: OmenaClosedWorldBundleV0;
}
export interface OmenaClosedWorldBundleV0 {
  readonly entrypoints: readonly OmenaModuleInstanceKeyV0[];
  readonly linkedModules: readonly OmenaModuleInstanceKeyV0[];
  readonly reachability: OmenaClosedWorldReachabilityIndexV0;
  readonly closureHash: string;
  readonly interfaceHashes?: OmenaClosedWorldInterfaceHashSetV0;
  readonly sourcePrecision?: OmenaClosedWorldSourcePrecisionSummaryV0;
}
export interface OmenaModuleInstanceKeyV0 {
  readonly module: string;
  readonly configuration: string;
}
export interface OmenaClosedWorldReachabilityIndexV0 {
  readonly moduleInstances: readonly OmenaModuleInstanceKeyV0[];
  readonly classNames: readonly string[];
  readonly keyframeNames: readonly string[];
  readonly valueNames: readonly string[];
  readonly customPropertyNames: readonly string[];
}
export interface OmenaClosedWorldInterfaceHashSetV0 {
  readonly entries: readonly OmenaClosedWorldInterfaceHashEntryV0[];
}
export interface OmenaClosedWorldInterfaceHashEntryV0 {
  readonly moduleInstance: OmenaModuleInstanceKeyV0;
  readonly availability: OmenaClosedWorldInterfaceHashAvailabilityV0;
}
export interface OmenaClosedWorldInterfaceHashKnownV0 {
  readonly status: "known";
  readonly interfaceHash: string;
}
export interface OmenaClosedWorldInterfaceHashAbsentV0 {
  readonly status: "absent";
}
export interface OmenaClosedWorldSourcePrecisionSummaryV0 {
  readonly exactSourceCount: number;
  readonly conservativeSourceCount: number;
  readonly heuristicSourceCount: number;
  readonly unknownSourceCount: number;
}
export interface OmenaClosedWorldOpenOutcomeV0 {
  readonly status: "open";
  readonly blockers: readonly OmenaClosedWorldBlockerV0[];
}
export interface OmenaClosedWorldEmptyEntrypointsBlockerV0 {
  readonly kind: "emptyEntrypoints";
}
export interface OmenaClosedWorldMissingEntrypointBlockerV0 {
  readonly kind: "missingEntrypoint";
  readonly sourcePath: string;
}
export interface OmenaClosedWorldAmbiguousModulePathBlockerV0 {
  readonly kind: "ambiguousModulePath";
  readonly sourcePath: string;
}
export interface OmenaClosedWorldMissingDependencyBlockerV0 {
  readonly kind: "missingDependency";
  readonly sourcePath: string;
  readonly importSource: string;
}
export interface OmenaClosedWorldMissingModuleInstanceBlockerV0 {
  readonly kind: "missingModuleInstance";
  readonly module: OmenaModuleInstanceKeyV0;
}
export interface OmenaClosedWorldMissingModuleDependencyBlockerV0 {
  readonly kind: "missingModuleDependency";
  readonly module: OmenaModuleInstanceKeyV0;
  readonly dependency: OmenaModuleInstanceKeyV0;
}
export interface OmenaClosedWorldPassUnavailableBlockerV0 {
  readonly kind: "closedWorldPassUnavailable";
  readonly requestedPassIds: readonly string[];
}
export interface OmenaClosedWorldDecisionParityV0 {
  readonly legacyOpenDecision: boolean;
  readonly typedOutcomeOpen: boolean;
  readonly equivalent: boolean;
}
export interface OmenaBundleEvidenceManifestV0 {
  readonly schemaVersion: "0";
  readonly product: "omena-query.bundle-evidence";
  readonly stylePath: string;
  readonly outcomeStatus: "closed" | "open";
  readonly reachability: OmenaBundleReachabilityEvidenceV0 | null;
  readonly gates: readonly OmenaBundleEvidenceGateV0[];
  readonly blockers: readonly OmenaClosedWorldBlockerV0[];
  readonly interfaceHashes: readonly OmenaClosedWorldInterfaceHashEntryV0[];
  readonly sourcePrecision: OmenaClosedWorldSourcePrecisionSummaryV0 | null;
}
export interface OmenaBundleReachabilityEvidenceV0 {
  readonly guarantee: OmenaGuaranteeKindV0;
  readonly interpretation: string;
  readonly moduleInstances: readonly OmenaModuleInstanceKeyV0[];
  readonly closureHash: string;
}
export interface OmenaBundleEvidenceGateV0 {
  readonly name: string;
  readonly passed: boolean;
}
