/* eslint-disable */
// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-sdk-workflow/main.tsp.
// Do not edit this file by hand.

export interface OmenaBundlerHostResolveModuleResponseV0 {
  readonly snapshotId: OmenaWorkspaceSnapshotIdV0;
  readonly protocolVersion: "0";
  readonly moduleId: string;
  readonly classMap: OmenaBundlerHostStringRecordV0;
  readonly namedExports: OmenaBundlerHostStringRecordV0;
  readonly typescriptDeclaration: string;
  readonly composesEdges: readonly OmenaBundlerHostComposesEdgeV0[];
  readonly diagnostics: readonly OmenaBundlerHostDiagnosticV0[];
  readonly ready: boolean;
}
export interface OmenaWorkspaceSnapshotIdV0 {
  readonly value: number;
}
export type OmenaBundlerHostStringRecordV0 = Readonly<Record<string, string>>;
export interface OmenaBundlerHostComposesEdgeV0 {
  readonly exportedName: string;
  readonly moduleId: string;
  readonly className: string;
}
export interface OmenaBundlerHostDiagnosticV0 {
  readonly code: string;
  readonly message: string;
}
