import { strict as assert } from "node:assert";
import fs from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(import.meta.dirname, "..");
const read = (relativePath: string) => fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
const injectUnregisteredHostEntryPoint = process.argv.includes(
  "--inject-unregistered-host-entry-point",
);
const pluginApi = read("rust/crates/omena-query-transform-runner/src/plugin_api.rs");
const pluginRegistry = read("rust/crates/omena-query-transform-runner/src/plugins/mod.rs");
const bundleHostPlugin = read(
  "rust/crates/omena-query-transform-runner/src/plugins/bundle_host.rs",
);
const semanticPlugin = read(
  "rust/crates/omena-query-transform-runner/src/plugins/semantic_observation.rs",
);
const adapter = read("packages/css-build-adapter/index.cjs");
const adapterTypes = read("packages/css-build-adapter/index.d.ts");
const generatedAdapterContract = read(
  "packages/css-build-adapter/bundler-host-contract.generated.d.ts",
);
const vite = read("packages/vite-plugin/index.cjs");
const bundlerProtocol = read("rust/crates/omena-query/src/bundler_host.rs");
const residualLedger = JSON.parse(read("rust/omena-bundler-host-residual-ledger.json")) as {
  readonly product: string;
  readonly entries: readonly {
    readonly id: string;
    readonly status: string;
    readonly owner: string;
    readonly reason: string;
  }[];
};

assert.match(pluginApi, /pub enum PluginKindV0\s*\{\s*Transform,\s*BundleHost,\s*\}/su);
assert.match(pluginApi, /pub kind: PluginKindV0,/u);
assert.equal(
  [...`${bundleHostPlugin}\n${semanticPlugin}`.matchAll(/kind:\s*PluginKindV0::BundleHost/gu)]
    .length,
  1,
  "exactly one built-in bundle host kind must be registered",
);
assert.ok(pluginRegistry.includes("&VITE_BUNDLE_HOST_PLUGIN"));
assert.ok(vite.includes('require("@omena/css-build-adapter")'));
assert.ok(adapter.includes("resolveCssModuleForBundlerHost"));
assert.ok(
  !vite.includes("resolveCssModuleForBundlerHost"),
  "Vite must consume the shared adapter instead of opening a second native host entry point",
);
const directJsBoundaryFiles = packageSourceFiles(path.join(repoRoot, "packages"))
  .filter((filePath) => {
    const source = fs.readFileSync(filePath, "utf8");
    return (
      source.includes("resolveCssModuleForBundlerHostJson") ||
      source.includes("resolveCssModuleForBundlerHost(")
    );
  })
  .map((filePath) => path.relative(repoRoot, filePath));
if (injectUnregisteredHostEntryPoint) {
  directJsBoundaryFiles.push("packages/unregistered-bundle-host/index.cjs");
}
assert.deepEqual(
  directJsBoundaryFiles.toSorted(),
  ["packages/css-build-adapter/index.cjs"],
  "native bundler-host access must stay behind the registered shared adapter entry point",
);
assert.ok(!bundleHostPlugin.includes("OMENA_BUNDLER_HOST_PROTOCOL_VERSION_V0"));
assert.ok(!bundlerProtocol.includes("OMENA_PLUGIN_ABI_VERSION_V0"));
assert.ok(
  generatedAdapterContract.includes(
    "@generated by scripts/generate-engine-v2-contract-idl.ts from contracts/engine-sdk-workflow/main.tsp",
  ),
  "the adapter contract must be generated from the SDK workflow TypeSpec authority",
);
assert.ok(adapterTypes.includes('from "./bundler-host-contract.generated"'));
assert.doesNotMatch(
  adapterTypes,
  /export interface OmenaBundlerHost(?:ResolveModuleResponse|ComposesEdge|Diagnostic)V0/u,
  "the adapter entry declaration must not redeclare generated bundler-host DTOs",
);
assert.equal(residualLedger.product, "omena.bundler-host-residual-ledger");
assert.deepEqual(residualLedger.entries.map(({ id }) => id).toSorted(), [
  "chunk-graph",
  "cross-chunk-css-order",
  "rspack-host",
  "source-map-passthrough-depth",
  "ssr-module-federation",
  "webpack-host",
]);
for (const entry of residualLedger.entries) {
  assert.ok(entry.status.length > 0, `${entry.id} must declare a status`);
  assert.ok(entry.owner.length > 0, `${entry.id} must declare an owner`);
  assert.ok(entry.reason.length > 0, `${entry.id} must explain why it remains residual`);
}
assert.deepEqual(
  residualLedger.entries.find(({ id }) => id === "chunk-graph"),
  {
    id: "chunk-graph",
    status: "unowned",
    owner: "unowned",
    reason:
      "No current component owns a chunk graph, so chunk-level host behavior must remain unavailable.",
  },
);

process.stdout.write(
  `${JSON.stringify({
    schemaVersion: "0",
    product: "js-bundler-host.plugin-kind",
    pluginKinds: ["transform", "bundleHost"],
    bundleHostRegistrationCount: 1,
    directJsBoundaryFileCount: directJsBoundaryFiles.length,
    versionAuthoritiesDistinct: true,
    adapterContractAuthority: "engine-sdk-workflow-typespec",
    residualEntryCount: residualLedger.entries.length,
  })}\n`,
);

function packageSourceFiles(root: string): string[] {
  const files: string[] = [];
  for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === "dist") continue;
    const filePath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...packageSourceFiles(filePath));
    } else if (
      entry.isFile() &&
      !entry.name.endsWith(".d.ts") &&
      /\.(?:cjs|mjs|js|cts|mts|ts|tsx)$/u.test(entry.name)
    ) {
      files.push(filePath);
    }
  }
  return files;
}
