import { strict as assert } from "node:assert";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const generatedRustPath = "rust/crates/omena-cascade/src/property_metadata_idl_generated.rs";
const helperPath = "rust/crates/omena-cascade/src/property_metadata.rs";
const computedValuePath = "rust/crates/omena-cascade/src/computed_value.rs";
const generatorPath = "scripts/generate-engine-v2-contract-idl.ts";
const generatedTypescriptPath =
  "server/engine-core-ts/src/contracts/property-metadata-idl.generated.ts";

const generatedRustSource = read(generatedRustPath);
const helperSource = read(helperPath);
const computedValueSource = read(computedValuePath);
const generatorSource = read(generatorPath);
const generatedTypescriptSource = read(generatedTypescriptPath);

const expectedRows = new Map([
  ["background-color", { inherited: false, initialValue: "transparent" }],
  ["border-color", { inherited: false, initialValue: "transparent" }],
  ["border-style", { inherited: false, initialValue: "none" }],
  ["border-width", { inherited: false, initialValue: "0" }],
  ["box-shadow", { inherited: false, initialValue: "none" }],
  ["caret-color", { inherited: false, initialValue: "transparent" }],
  ["color", { inherited: true, initialValue: "canvastext" }],
  ["cursor", { inherited: true, initialValue: "auto" }],
  ["direction", { inherited: true, initialValue: "initial" }],
  ["display", { inherited: false, initialValue: "none" }],
  ["font", { inherited: true, initialValue: "initial" }],
  ["font-family", { inherited: true, initialValue: "serif" }],
  ["font-size", { inherited: true, initialValue: "medium" }],
  ["font-style", { inherited: true, initialValue: "normal" }],
  ["font-variant", { inherited: true, initialValue: "normal" }],
  ["font-weight", { inherited: true, initialValue: "normal" }],
  ["letter-spacing", { inherited: true, initialValue: "normal" }],
  ["line-height", { inherited: true, initialValue: "normal" }],
  ["margin", { inherited: false, initialValue: "0" }],
  ["opacity", { inherited: false, initialValue: "1" }],
  ["outline-color", { inherited: false, initialValue: "transparent" }],
  ["padding", { inherited: false, initialValue: "0" }],
  ["text-align", { inherited: true, initialValue: "start" }],
  ["text-indent", { inherited: true, initialValue: "0" }],
  ["text-shadow", { inherited: false, initialValue: "none" }],
  ["text-transform", { inherited: true, initialValue: "none" }],
  ["visibility", { inherited: true, initialValue: "visible" }],
  ["white-space", { inherited: true, initialValue: "normal" }],
  ["word-spacing", { inherited: true, initialValue: "normal" }],
] as const);

assert.ok(
  generatorSource.includes("contracts/property-metadata/main.tsp"),
  "property metadata must be generated by the existing contract IDL generator",
);
assert.ok(
  generatorSource.includes(generatedRustPath),
  "generated Rust property metadata artifact must be tracked by the generator",
);
assert.ok(
  generatorSource.includes(generatedTypescriptPath),
  "generated TypeScript property metadata artifact must be tracked by the generator",
);
assert.ok(
  generatedTypescriptSource.includes("export interface CssPropertyMetadataV1Json"),
  "TypeScript property metadata IDL must be generated",
);
assert.ok(
  generatedRustSource.includes("pub const CSS_PROPERTY_METADATA_V1"),
  "Rust property metadata DB must be generated",
);
assert.ok(
  generatedRustSource.includes('package: "@webref/css"'),
  "property metadata source must carry the webref package pin",
);
assert.ok(
  generatedRustSource.includes('initial_value: "guaranteed-invalid"'),
  "custom property initial policy must be represented in the generated DB",
);

const actualRows = parseGeneratedRows(generatedRustSource);
assert.equal(actualRows.size, expectedRows.size, "generated property row count changed");

for (const [property, expected] of expectedRows) {
  const actual = actualRows.get(property);
  assert.ok(actual, `missing generated property metadata row for ${property}`);
  assert.equal(actual.canonicalName, property, `${property} canonical name drifted`);
  assert.equal(actual.inherited, expected.inherited, `${property} inheritance verdict drifted`);
  assert.equal(
    actual.initialValue,
    expected.initialValue,
    `${property} initial value verdict drifted`,
  );
}

assert.ok(
  [...actualRows.values()].some((row) => row.inherited),
  "property metadata DB must contain inherited properties",
);
assert.ok(
  new Set([...actualRows.values()].map((row) => row.initialValue)).size > 1,
  "property metadata DB must contain non-vacuous initial values",
);
assert.ok(
  helperSource.includes("CSS_PROPERTY_METADATA_RECORDS_V1"),
  "runtime helper must read from the generated property metadata DB",
);
assert.ok(
  computedValueSource.includes("css_property_is_inherited"),
  "computed-value inheritance reader must route through property metadata",
);
assert.ok(
  computedValueSource.includes("css_property_initial_value"),
  "computed-value initial reader must route through property metadata",
);
assert.ok(
  !computedValueSource.includes("matches!("),
  "computed-value module must not keep a second inherited-property match table",
);
assert.ok(
  !computedValueSource.includes("match property {"),
  "computed-value module must not keep a second initial-value match table",
);

process.stdout.write(
  `${JSON.stringify(
    {
      schemaVersion: "0",
      product: "omena-cascade.property-metadata",
      rowCount: actualRows.size,
      inheritedRowCount: [...actualRows.values()].filter((row) => row.inherited).length,
      initialValueCount: new Set([...actualRows.values()].map((row) => row.initialValue)).size,
      complete: true,
    },
    null,
    2,
  )}\n`,
);

function parseGeneratedRows(
  source: string,
): Map<string, { canonicalName: string; inherited: boolean; initialValue: string }> {
  const rows = new Map<
    string,
    { canonicalName: string; inherited: boolean; initialValue: string }
  >();
  const rowPattern =
    /CssPropertyMetadataRecordStaticV1\s*\{\s*property_id:\s*"([^"]+)",\s*canonical_name:\s*"([^"]+)",\s*inherited:\s*(true|false),\s*initial_value:\s*"([^"]+)",\s*\}/gu;

  for (const match of source.matchAll(rowPattern)) {
    const [, propertyId, canonicalName, inherited, initialValue] = match;
    assert.ok(propertyId, "generated row property id must be present");
    assert.ok(canonicalName, "generated row canonical name must be present");
    assert.ok(inherited, "generated row inherited verdict must be present");
    assert.ok(initialValue, "generated row initial value must be present");
    assert.ok(!rows.has(propertyId), `duplicate generated property metadata row: ${propertyId}`);
    rows.set(propertyId, {
      canonicalName,
      inherited: inherited === "true",
      initialValue,
    });
  }

  return rows;
}

function read(relativePath: string): string {
  return fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
}
