// @generated by scripts/generate-engine-v2-contract-idl.ts from contracts/external-corpus-envelope/main.tsp.
// Do not edit this file by hand.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ExternalCorpusStageV1Json {
    #[serde(rename = "stage1-advisory")]
    Stage1Advisory,
    #[serde(rename = "stage2-blocking")]
    Stage2Blocking,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ExternalCorpusDialectV1Json {
    #[serde(rename = "css")]
    Css,
    #[serde(rename = "scss")]
    Scss,
    #[serde(rename = "sass")]
    Sass,
    #[serde(rename = "less")]
    Less,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ExternalCorpusExpectationKindV1Json {
    #[serde(rename = "static-must-match")]
    StaticMustMatch,
    #[serde(rename = "expected-sound-bail")]
    ExpectedSoundBail,
    #[serde(rename = "parser-recovery")]
    ParserRecovery,
    #[serde(rename = "out-of-scope")]
    OutOfScope,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalCorpusSourcePinV1Json {
    pub repository: String,
    pub pin: String,
    pub sparse_paths: Vec<String>,
    pub helper_classes: Vec<String>,
    pub layout_dependent_helpers_excluded: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalCorpusKnownFailurePolicyRefV1Json {
    pub path: String,
    pub schema_version: String,
    pub stage2_blocking: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalCorpusGenerationProvenanceV1Json {
    pub tool: String,
    pub selection_path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oracle_pin_refs: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalCorpusSparsePathFixtureCountV1Json {
    pub sparse_path: String,
    pub fixture_count: i32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalCorpusChunkV1Json {
    pub chunk_id: String,
    pub path: String,
    pub stage: ExternalCorpusStageV1Json,
    pub sha256: String,
    pub fixture_count: i32,
    pub sparse_path_fixture_counts: Vec<ExternalCorpusSparsePathFixtureCountV1Json>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalCorpusProvenanceV1Json {
    pub generation_tool: String,
    pub selection_path: String,
    pub oracle_pin_refs: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalCorpusGreenRunV1Json {
    pub date: String,
    pub commit: String,
    pub fixture_count: i32,
    pub chunk_sha256: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outcome_olw: Option<i32>,
    pub critical_regression_count: i32,
    pub command: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalCorpusEnvelopeV1Json {
    pub schema_version: String,
    pub product: String,
    pub stage: ExternalCorpusStageV1Json,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dialect: Option<ExternalCorpusDialectV1Json>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expectation_kind: Option<ExternalCorpusExpectationKindV1Json>,
    pub source: ExternalCorpusSourcePinV1Json,
    pub known_failure_policy: ExternalCorpusKnownFailurePolicyRefV1Json,
    pub generation: ExternalCorpusGenerationProvenanceV1Json,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provenance: Option<ExternalCorpusProvenanceV1Json>,
    pub sparse_path_fixture_counts: Vec<ExternalCorpusSparsePathFixtureCountV1Json>,
    pub chunks: Vec<ExternalCorpusChunkV1Json>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub green_runs: Option<Vec<ExternalCorpusGreenRunV1Json>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalCorpusDifferentialManifestV1Json {
    pub schema_version: String,
    pub product: String,
    pub mode: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_verified: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compilers: Option<serde_json::Value>,
    pub fixtures: Vec<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalCorpusDisagreementLedgerV1Json {
    pub schema_version: String,
    pub product: String,
    pub allowlist_count: i32,
    pub entries: Vec<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExternalCorpusSeedPolicyV1Toml {
    #[serde(rename = "schema_version")]
    pub schema_version: String,
    #[serde(rename = "corpus_manifest")]
    pub corpus_manifest: String,
    pub stage: String,
    #[serde(rename = "stage2_blocking")]
    pub stage2_blocking: bool,
    #[serde(rename = "source_pin")]
    pub source_pin: String,
    #[serde(rename = "review_interval_days")]
    pub review_interval_days: i32,
    #[serde(rename = "required_min_fixture_count_for_stage2")]
    pub required_min_fixture_count_for_stage2: i32,
    #[serde(rename = "required_consecutive_green_runs")]
    pub required_consecutive_green_runs: i32,
    #[serde(rename = "consecutive_green_runs")]
    pub consecutive_green_runs: i32,
    #[serde(default)]
    pub green_run: Vec<ExternalCorpusSeedPolicyGreenRunV1Toml>,
    #[serde(default)]
    pub subtest: Vec<ExternalCorpusSeedPolicySubtestV1Toml>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExternalCorpusSeedPolicyGreenRunV1Toml {
    pub date: String,
    pub commit: String,
    #[serde(rename = "fixture_count")]
    pub fixture_count: i32,
    #[serde(rename = "chunk_sha256")]
    pub chunk_sha256: String,
    #[serde(rename = "outcome_olw")]
    pub outcome_olw: i32,
    #[serde(rename = "critical_regression_count")]
    pub critical_regression_count: i32,
    pub command: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExternalCorpusSeedPolicySubtestV1Toml {
    pub fixture: String,
    pub name: String,
    pub status: String,
    pub reason: String,
    pub issue: String,
    pub since: String,
    #[serde(rename = "review_after")]
    pub review_after: String,
}
